/** Chrome + shared UI strings: top bar, masthead, nav, footer, login, sidebar, errors. */
export const dict = {
  en: {
    // gov top bar
    'top.gov': 'भारत सरकार · Government of India',
    // masthead
    'mast.tagline': 'Vertical Property Mapping & Spatial Governance',
    'mast.demo': 'PROTOTYPE · DEMO DATA',
    'mast.workspace': 'Go to workspace',
    'mast.login': 'Login / Register',
    // footer
    'foot.about': 'Vertical property mapping and spatial governance prototype — parcel → building → floor → unit as 3D volumes, with AI-assisted validation and QR identity.',
    'foot.quick': 'Quick Links',
    'foot.services': 'Citizen Services',
    'foot.helpdesk': 'Helpdesk (Demo)',
    'foot.phone': '1800-XXX-XXXX (Toll free, demo)',
    'foot.addr': 'Land Records Demo Cell, New Delhi — 110001',
    'foot.contact': 'Contact us →',
    'foot.verify': 'Verify property identity',
    'foot.submit': 'Submit property data',
    'foot.track': 'Track submission',
    'foot.workflow': 'Submission workflow',
    'foot.faq': 'FAQs & guides',
    'foot.inspired': 'This prototype is inspired by DILRMP · ULPIN (Bhu-Aadhaar) · Bhu-Naksha · India.gov.in design patterns.',
    'foot.last': 'SIH 2026 Prototype · For demonstration only · Last updated Sept 2026',
    // login
    'login.back': 'Back to portal home',
    'login.sih': 'SIH 2026 · Problem Statement 26011',
    'login.vert': 'Vertical Property Mapping & Spatial Governance',
    'login.title': 'Sign in',
    'login.sub': 'Mock authentication · pick a demo role to explore its workspace',
    'login.role': 'Demo role',
    'login.pw': 'Password',
    'login.fail': 'Sign-in failed. Use a demo role with password demo123.',
    'login.signing': 'Signing in…',
    'login.portal': 'Sign in to service portal',
    'login.dash': 'Sign in to dashboard',
    'login.allpw': 'All demo roles use password',
    'login.help': 'Need help?',
    'login.officer': 'Government Officer',
    'login.officerD': 'Review, approve & resolve conflicts',
    'login.surveyor': 'Surveyor',
    'login.surveyorD': 'Field visits & department filings',
    'login.admin': 'Administrator',
    'login.adminD': 'Datasets, rules & analytics',
    'login.citizen': 'Property Owner / Citizen',
    'login.citizenD': 'Submit property data for verification',
    'login.p1': 'Parcel → building → floor → unit as 3D spatial volumes',
    'login.p2': 'GIS, LiDAR, drone, GNSS & floor-plan evidence fusion',
    'login.p3': 'AI-assisted topology validation + confidence scoring',
    'login.p4': 'QR digital identity for every property',
    'login.disclaimer': 'Prototype identifiers are demo references — not official Government of India ULPINs.',
    // layout sidebar
    'side.services': 'My Services',
    'side.home': 'Home',
    'side.submit': 'Submit Property',
    'side.my': 'My Submissions',
    'side.verify': 'Verify Property',
    'side.explore': 'Explore',
    'side.map': '2D Map',
    'side.view3d': '3D View',
    'side.help': 'Help',
    'side.faq': 'Help / FAQ',
    'side.contact': 'Contact Us',
    'side.workspace': 'Workspace',
    'side.dash': 'Dashboard',
    'side.cadastre': '3D Cadastre',
    'side.govern': 'Govern',
    'side.validation': 'Validation',
    'side.infra': 'Infrastructure',
    'side.reports': 'Reports',
    'side.submitData': 'Submit Data',
    'side.field': 'Field Work',
    'side.queue': 'Verify Queue',
    'side.system': 'System',
    'side.admin': 'Admin',
    'side.copilot': 'AI Copilot',
    'side.demo': 'demo session',
    'side.logout': 'Logout',
    'side.portalHome': 'Portal Home',
    'side.publicPortal': 'Public Portal',
    // layout header
    'head.title': 'Vertical Property Mapping & Spatial Governance',
    'head.search': 'Search ULPIN, parcel, building…',
    'head.tour': 'Present',
    // notifs
    'notif.title': 'Notifications',
    'notif.empty': 'No notifications.',
    'notif.head': 'NOTIFICATIONS',
    // misc shared
    'c.loading': 'Loading…',
    'c.retry': 'Retry',
    'c.back': 'Back',
    'c.next': 'Next',
    'c.close': 'Close',
    'c.cancel': 'Cancel',
    'c.save': 'Save',
    'c.search': 'Search',
    'c.viewAll': 'View all',
    'c.downloadPng': 'Download PNG',
    'c.downloadPdf': 'Download PDF',
    'c.preparing': 'Preparing…',
    'c.dlFail': 'Download failed in this browser. Try the other format.',
    'c.open3d': 'Open in 3D',
    'c.caseFile': 'Case file →',
    'c.prev': 'Prev',
    // feedback
    'fb.error': 'Something went wrong',
    'fb.home': 'Back to home',
    'fb.oops': 'Page not found',
    'fb.oopsSub': "The view you asked for doesn't exist in this demo.",
    'fb.homeBtn': 'Home',
    'fb.verifyBtn': 'Verify property',
    // status labels (ui)
    'st.confidence': 'confidence',
    'st.Verified': 'Verified',
    'st.HighConf': 'High Confidence',
    'st.NeedsReview': 'Needs Review',
    'st.Unverified': 'Unverified',
    'st.Open': 'Open',
    'st.Resolved': 'Resolved',
    'st.UnderReview': 'Under Review',
    'st.Rejected': 'Rejected',
    'st.High': 'High',
    'st.Medium': 'Medium',
    'st.Low': 'Low',
    // breadcrumbs + shared grid labels + notices
    'trail.home': 'Home',
    'trail.about': 'About Us',
    'trail.services': 'Services',
    'trail.how': 'How It Works',
    'trail.verify': 'Verify Property',
    'trail.help': 'Help / FAQ',
    'trail.contact': 'Contact Us',
    'g.parcel': 'Parcel',
    'g.building': 'Building',
    'g.floor': 'Floor',
    'g.unit': 'Unit',
    'g.area': 'Area',
    'g.vertical': 'Vertical',
    'c.protoNotice': 'Prototype 3D cadastral reference — NOT an official Government of India ULPIN.',
    'c.protoUlp': 'Prototype 3D ULPIN',
    'c.open3dArrow': 'Open in 3D →',
    'nav.menu': 'Menu',
    'nav.toggle': 'Toggle navigation',
    'login.portalHome': 'Portal home',
    'home.open': 'Open →',
    'home.svcOpen': 'Open service →',
    'home.i1': '3D volumes',
    'home.i2': 'GIS + LiDAR',
    'home.i3': 'QR identity',
    // about page bodies
    'about.p1': 'DILRMP — modern, transparent land-records management; RoR + cadastral map integration.',
    'about.p2': 'ULPIN / Bhu-Aadhaar — single authoritative parcel identity (14-digit nationally; extended demo references here for 3D stacking).',
    'about.p3': 'Bhu-Naksha / NGDRS concepts — map-based services, registration linkages, citizen access.',
    'about.is1': 'Interactive 2D map + 3D tower demo on synthetic data',
    'about.is2': 'Citizen submit → officer verify workflow with audit trail',
    'about.is3': 'Public QR identity with safe fields only',
    'about.is4': 'Validation centre showing evidence + confidence honestly',
    'about.not1': 'Not an official Government of India website.',
    'about.not2': 'Demo ULPIN-like IDs are not real Bhu-Aadhaar numbers.',
    'about.not3': 'Submissions and AI scores do not confer legal ownership.',
    'about.not4': 'City-scale counts on staff screens are illustrative, not census data.',
    // help demo accounts + contact topics
    'help.dCitizen': 'Property owner — submit & track',
    'help.dOfficer': 'Verify queue + approvals',
    'help.dSurveyor': 'Field checks + geometry',
    'help.dAdmin': 'Datasets + audit',
    'ct.t1': 'Property submission',
    'ct.t2': 'Verification / ULPIN',
    'ct.t3': 'Map / 3D issue',
    'ct.t4': 'Grievance (demo)',
    'ct.t5': 'Other',
    'ch.disclaimer': 'Prototype identifiers are demo references — not official Government of India ULPINs. Submissions are unverified claims until approved and never establish legal ownership.',
    // identity facts fragments
    'facts.floorW': 'floor',
    'facts.blockW': 'block',
    'facts.parcelW': 'parcel',
    'facts.survey': 'Survey {n}',
    'facts.parcelBld': 'Parcel {x} · Building {y}',
    'facts.ownerRecV': 'Owner record verified',
    'facts.ownerRecP': 'Owner record pending',
  },
  hi: {
    'top.gov': 'भारत सरकार · Government of India',
    'mast.tagline': 'त्रि-आयामी संपत्ति मानचित्रण एवं स्थानिक शासन',
    'mast.demo': 'प्रोटोटाइप · डेमो डेटा',
    'mast.workspace': 'कार्यक्षेत्र पर जाएं',
    'mast.login': 'लॉगिन / पंजीकरण',
    'foot.about': 'त्रि-आयामी संपत्ति मानचित्रण और स्थानिक शासन प्रोटोटाइप — पार्सल → भवन → तल → इकाई 3D आयतन के रूप में, AI-सहायित सत्यापन और QR पहचान सहित।',
    'foot.quick': 'त्वरित लिंक',
    'foot.services': 'नागरिक सेवाएं',
    'foot.helpdesk': 'हेल्पडेस्क (डेमो)',
    'foot.phone': '1800-XXX-XXXX (टोल फ्री, डेमो)',
    'foot.addr': 'भू-अभिलेख डेमो प्रकोष्ठ, नई दिल्ली — 110001',
    'foot.contact': 'संपर्क करें →',
    'foot.verify': 'संपत्ति पहचान सत्यापित करें',
    'foot.submit': 'संपत्ति डेटा जमा करें',
    'foot.track': 'आवेदन ट्रैक करें',
    'foot.workflow': 'जमा करने की प्रक्रिया',
    'foot.faq': 'सामान्य प्रश्न व मार्गदर्शिकाएं',
    'foot.inspired': 'यह प्रोटोटाइप DILRMP · ULPIN (भू-आधार) · भू-नक्शा · India.gov.in डिज़ाइन से प्रेरित है।',
    'foot.last': 'SIH 2026 प्रोटोटाइप · केवल प्रदर्शन हेतु · अंतिम अद्यतन सितंबर 2026',
    'login.back': 'पोर्टल होम पर वापस जाएं',
    'login.sih': 'SIH 2026 · समस्या विवरण 26011',
    'login.vert': 'त्रि-आयामी संपत्ति मानचित्रण एवं स्थानिक शासन',
    'login.title': 'साइन इन',
    'login.sub': 'डेमो प्रमाणीकरण · अपना कार्यक्षेत्र देखने हेतु डेमो भूमिका चुनें',
    'login.role': 'डेमो भूमिका',
    'login.pw': 'पासवर्ड',
    'login.fail': 'साइन-इन विफल। पासवर्ड demo123 के साथ डेमो भूमिका प्रयोग करें।',
    'login.signing': 'साइन इन हो रहा है…',
    'login.portal': 'सेवा पोर्टल में साइन इन करें',
    'login.dash': 'डैशबोर्ड में साइन इन करें',
    'login.allpw': 'सभी डेमो भूमिकाओं का पासवर्ड है',
    'login.help': 'सहायता चाहिए?',
    'login.officer': 'सरकारी अधिकारी',
    'login.officerD': 'समीक्षा, अनुमोदन व विवाद समाधान',
    'login.surveyor': 'सर्वेक्षक',
    'login.surveyorD': 'क्षेत्र भ्रमण व विभागीय प्रविष्टियां',
    'login.admin': 'प्रशासक',
    'login.adminD': 'डेटासेट, नियम व विश्लेषण',
    'login.citizen': 'संपत्ति स्वामी / नागरिक',
    'login.citizenD': 'सत्यापन हेतु संपत्ति डेटा जमा करें',
    'login.p1': 'पार्सल → भवन → तल → इकाई 3D स्थानिक आयतन के रूप में',
    'login.p2': 'GIS, LiDAR, ड्रोन, GNSS व फ्लोर-प्लान साक्ष्य समन्वय',
    'login.p3': 'AI-सहायित टोपोलॉजी सत्यापन + विश्वास स्कोर',
    'login.p4': 'प्रत्येक संपत्ति हेतु QR डिजिटल पहचान',
    'login.disclaimer': 'प्रोटोटाइप पहचानकर्ता डेमो संदर्भ हैं — भारत सरकार के आधिकारिक ULPIN नहीं।',
    'side.services': 'मेरी सेवाएं',
    'side.home': 'होम',
    'side.submit': 'संपत्ति जमा करें',
    'side.my': 'मेरे आवेदन',
    'side.verify': 'संपत्ति सत्यापित करें',
    'side.explore': 'एक्सप्लोर',
    'side.map': '2D मानचित्र',
    'side.view3d': '3D दृश्य',
    'side.help': 'सहायता',
    'side.faq': 'सहायता / सामान्य प्रश्न',
    'side.contact': 'संपर्क करें',
    'side.workspace': 'कार्यक्षेत्र',
    'side.dash': 'डैशबोर्ड',
    'side.cadastre': '3D भू-मानचित्र',
    'side.govern': 'शासन',
    'side.validation': 'सत्यापन',
    'side.infra': 'अवसंरचना',
    'side.reports': 'रिपोर्ट',
    'side.submitData': 'डेटा जमा करें',
    'side.field': 'क्षेत्र कार्य',
    'side.queue': 'सत्यापन कतार',
    'side.system': 'सिस्टम',
    'side.admin': 'प्रशासन',
    'side.copilot': 'AI सहायक',
    'side.demo': 'डेमो सत्र',
    'side.logout': 'लॉगआउट',
    'side.portalHome': 'पोर्टल होम',
    'side.publicPortal': 'सार्वजनिक पोर्टल',
    'head.title': 'त्रि-आयामी संपत्ति मानचित्रण एवं स्थानिक शासन',
    'head.search': 'ULPIN, पार्सल, भवन खोजें…',
    'head.tour': 'प्रस्तुति',
    'notif.title': 'सूचनाएं',
    'notif.empty': 'कोई सूचना नहीं।',
    'notif.head': 'सूचनाएं',
    'c.loading': 'लोड हो रहा है…',
    'c.retry': 'पुनः प्रयास',
    'c.back': 'पीछे',
    'c.next': 'आगे',
    'c.close': 'बंद करें',
    'c.cancel': 'रद्द करें',
    'c.save': 'सहेजें',
    'c.search': 'खोजें',
    'c.viewAll': 'सभी देखें',
    'c.downloadPng': 'PNG डाउनलोड करें',
    'c.downloadPdf': 'PDF डाउनलोड करें',
    'c.preparing': 'तैयार हो रहा है…',
    'c.dlFail': 'इस ब्राउज़र में डाउनलोड विफल। दूसरा प्रारूप आज़माएं।',
    'c.open3d': '3D में खोलें',
    'c.caseFile': 'केस फ़ाइल →',
    'c.prev': 'पिछला',
    'fb.error': 'कुछ गलत हो गया',
    'fb.home': 'होम पर वापस जाएं',
    'fb.oops': 'पृष्ठ नहीं मिला',
    'fb.oopsSub': 'आपने जो दृश्य मांगा वह इस डेमो में नहीं है।',
    'fb.homeBtn': 'होम',
    'fb.verifyBtn': 'संपत्ति सत्यापित करें',
    'st.confidence': 'विश्वास',
    'st.Verified': 'सत्यापित',
    'st.HighConf': 'उच्च विश्वास',
    'st.NeedsReview': 'समीक्षा आवश्यक',
    'st.Unverified': 'असत्यापित',
    'st.Open': 'खुला',
    'st.Resolved': 'समाधानित',
    'st.UnderReview': 'समीक्षाधीन',
    'st.Rejected': 'अस्वीकृत',
    'st.High': 'उच्च',
    'st.Medium': 'मध्यम',
    'st.Low': 'निम्न',
    'trail.home': 'होम',
    'trail.about': 'हमारे बारे में',
    'trail.services': 'सेवाएं',
    'trail.how': 'यह कैसे काम करता है',
    'trail.verify': 'संपत्ति सत्यापित करें',
    'trail.help': 'सहायता / सामान्य प्रश्न',
    'trail.contact': 'संपर्क करें',
    'g.parcel': 'पार्सल',
    'g.building': 'भवन',
    'g.floor': 'तल',
    'g.unit': 'इकाई',
    'g.area': 'क्षेत्र',
    'g.vertical': 'ऊंचाई',
    'c.protoNotice': 'प्रोटोटाइप 3D भू-अभिलेख संदर्भ — भारत सरकार का आधिकारिक ULPIN नहीं।',
    'c.protoUlp': 'प्रोटोटाइप 3D ULPIN',
    'c.open3dArrow': '3D में खोलें →',
    'nav.menu': 'मेनू',
    'nav.toggle': 'नेविगेशन टॉगल करें',
    'login.portalHome': 'पोर्टल होम',
    'home.open': 'खोलें →',
    'home.svcOpen': 'सेवा खोलें →',
    'home.i1': '3D आयतन',
    'home.i2': 'GIS + LiDAR',
    'home.i3': 'QR पहचान',
    'about.p1': 'DILRMP — आधुनिक, पारदर्शी भू-अभिलेख प्रबंधन; RoR + भू-मानचित्र एकीकरण।',
    'about.p2': 'ULPIN / भू-आधार — एकल आधिकारिक पार्सल पहचान (राष्ट्रीय स्तर पर 14-अंकीय; 3D स्तरण हेतु यहां विस्तारित डेमो संदर्भ)।',
    'about.p3': 'भू-नक्शा / NGDRS अवधारणाएं — मानचित्र-आधारित सेवाएं, पंजीकरण लिंकेज, नागरिक पहुंच।',
    'about.is1': 'कृत्रिम डेटा पर इंटरैक्टिव 2D मानचित्र + 3D टावर डेमो',
    'about.is2': 'ऑडिट ट्रेल सहित नागरिक आवेदन → अधिकारी सत्यापन कार्यप्रवाह',
    'about.is3': 'केवल सुरक्षित फ़ील्ड सहित सार्वजनिक QR पहचान',
    'about.is4': 'साक्ष्य + विश्वास ईमानदारी से दिखाता सत्यापन केंद्र',
    'about.not1': 'भारत सरकार की आधिकारिक वेबसाइट नहीं।',
    'about.not2': 'डेमो ULPIN-सदृश ID वास्तविक भू-आधार संख्याएं नहीं हैं।',
    'about.not3': 'आवेदन और AI स्कोर कानूनी स्वामित्व प्रदान नहीं करते।',
    'about.not4': 'स्टाफ स्क्रीन पर शहर-स्तरीय गणनाएं सचित्र हैं, जनगणना डेटा नहीं।',
    'help.dCitizen': 'संपत्ति स्वामी — जमा व ट्रैक करें',
    'help.dOfficer': 'सत्यापन कतार + अनुमोदन',
    'help.dSurveyor': 'क्षेत्र जांच + ज्यामिति',
    'help.dAdmin': 'डेटासेट + ऑडिट',
    'ct.t1': 'संपत्ति आवेदन',
    'ct.t2': 'सत्यापन / ULPIN',
    'ct.t3': 'मानचित्र / 3D समस्या',
    'ct.t4': 'शिकायत (डेमो)',
    'ct.t5': 'अन्य',
    'ch.disclaimer': 'प्रोटोटाइप पहचानकर्ता डेमो संदर्भ हैं — भारत सरकार के आधिकारिक ULPIN नहीं। आवेदन अनुमोदन तक असत्यापित दावे हैं और कभी कानूनी स्वामित्व स्थापित नहीं करते।',
    'facts.floorW': 'तल',
    'facts.blockW': 'ब्लॉक',
    'facts.parcelW': 'पार्सल',
    'facts.survey': 'सर्वे {n}',
    'facts.parcelBld': 'पार्सल {x} · भवन {y}',
    'facts.ownerRecV': 'स्वामी अभिलेख सत्यापित',
    'facts.ownerRecP': 'स्वामी अभिलेख लंबित',
  },
};
