/** Workspace strings: dashboard, submit wizard, track, queue, field work, map, 3D, ops, copilot, tour. */
export const dict = {
  en: {
    // dashboard
    'dash.load': 'Loading staff dashboard…',
    'dash.err': 'Could not load statistics.',
    'dash.title': 'Staff dashboard',
    'dash.sub': '· Operational register for officers / surveyors / admins. Citizens use the service portal instead.',
    'dash.portal': 'Service portal →',
    'dash.glance': 'At a glance',
    'dash.liveNote': 'Live demo dataset — every number is a real record below',
    'dash.cityNote': 'Illustrative city-scale register — switch to Live demo for real records',
    'dash.city': 'City scale',
    'dash.live': 'Live demo',
    'dash.parcels': 'Total Parcels',
    'dash.buildings': 'Total Buildings',
    'dash.units': 'Registered Units',
    'dash.verified': 'Verified',
    'dash.needs': 'Needs Review',
    'dash.spatial': 'Spatial Conflicts',
    'dash.owner': 'Ownership Conflicts',
    'dash.under': 'Underground Assets',
    'dash.avg': 'Avg Confidence',
    'dash.flag': 'Flagship demo: Green Residency',
    'dash.flagS': '3 towers · 12/10/15 floors · B1/B2',
    'dash.openMap': 'Open map',
    'dash.open3d': 'Open 3D',
    'dash.quality': 'Spatial quality',
    'dash.qualityS': 'Live demo validation signal',
    'dash.sev': 'Open issues by severity',
    'dash.mix': 'Verification mix (demo)',
    'dash.needsR': 'Needs review',
    'dash.intake': 'Submission intake',
    'dash.intakeS': 'Property data flowing into the cadastre',
    'dash.total': 'Total',
    'dash.pending': 'Pending verification',
    'dash.citizen': 'Citizen',
    'dash.govt': 'Government',
    'dash.myField': 'My field work',
    'dash.field': 'Field work',
    'dash.fieldS': 'Site visits assigned to you',
    'dash.fieldAll': 'Field verification workload',
    'dash.openV': 'Open visits',
    'dash.doneV': 'Completed',
    'dash.myFilings': 'My department filings',
    'dash.startFiling': 'Start govt filing',
    'dash.siteReq': 'Site visit required',
    'dash.openArrow': 'Open →',
    'dash.attn': 'Needs attention',
    'dash.attnS': 'Latest validation findings — click through to the Validation Center',
    'dash.noIssues': 'No open issues.',
    // submit landing + wizard (core actions; long form labels stay bilingual via code fallback)
    'sub.title': 'Property Data Submission',
    'sub.sub': 'Submit or update property information for integration into the 3D cadastral system.',
    'sub.ownerCard': 'Property Owner / Citizen',
    'sub.ownerD': 'Submit or update your property information. Citizen submissions are reviewed by an authorized government officer before becoming verified cadastral information.',
    'sub.govtCard': 'Government / Authorized Department',
    'sub.govtD': 'Submit authenticated property, land, building, infrastructure, or spatial information from an authorized department.',
    'sub.govtNote': 'Authorized source: automatic technical validation, no citizen verification queue.',
    'sub.asOwner': 'Submit as Property Owner',
    'sub.asGovt': 'Submit as Government Department',
    'sub.needCitizen': 'Sign in as citizen (demo123) to submit as a property owner.',
    'sub.needGovt': 'Requires an officer, surveyor or admin account.',
    'sub.mySubs': 'My Submissions',
    'sub.myField': 'My Field Work',
    'sub.queue': 'Verification Queue',
    'sub.allField': 'All Field Work',
    'sub.flow': 'Flow: submission → automatic validation → human verification → approval → live record.',
    'sub.needsAuth': 'Property submission needs a citizen or government account. Sign in as citizen (demo123) to continue.',
    'sub.opening': 'Opening draft…',
    'sub.success': 'Submission Successful',
    'sub.govtDone': 'Authorized department source recorded. Automatic validation ran; the record is integrated or flagged for review — never the citizen queue.',
    'sub.ownerDone': 'Your property information has been submitted successfully. An authorized officer will verify it before it becomes verified cadastral data.',
    'sub.track': 'Track Submission',
    'sub.newHead': 'New Property Submission',
    'sub.govtMode': 'Authorized department source — automatic validation, no citizen queue.',
    'sub.ownerMode': 'Owner submission — human verification required before it becomes cadastral data.',
    'sub.fillDemo': 'Fill demo data',
    'sub.fillTitle': 'Fill the whole form with demo data for showcase',
    'sub.saveDraft': 'Save Draft',
    'sub.saved': 'Draft saved',
    'sub.saveFail': 'Save failed: {e}',
    'sub.back': 'Back',
    'sub.continue': 'Continue',
    'sub.submitBtn': 'Submit Property Data',
    'sub.submitFail': 'Submit failed: {e}',
    'sub.declare': 'Please accept the declaration',
    'sub.review': 'Review & declaration',
    'sub.declare1': 'I declare the information is true to my knowledge. I understand',
    'sub.declareGovt': 'it enters as an authorized department source after technical validation.',
    'sub.declareOwner': 'ownership details are claims pending verification and do not establish legal ownership.',
    'sub.what': 'What do you want to do?',
    'sub.newKind': 'Register / Submit New Property',
    'sub.newKindD': 'First-time intake for this property',
    'sub.updKind': 'Update Existing Property',
    'sub.updKindD': 'Correct or extend a record already in the system',
    'sub.find': 'Find existing property',
    'sub.findH': 'ULPIN, parcel, building, unit, survey no. or address — reuses global search',
    'sub.pickMap': 'Select Property on Map',
    'sub.linked': 'Linked: {v}',
    'sub.propLoc': 'Property & location',
    'sub.propType': 'Property type',
    'sub.propName': 'Property name',
    'sub.parcel': 'Parcel',
    'sub.parcelId': 'Parcel ID',
    'sub.building': 'Building',
    'sub.floor': 'Floor',
    'sub.unit': 'Apartment / Unit',
    'sub.addr': 'Address & coordinates',
    'sub.pickLoc': 'Pick location on map',
    'sub.meas': 'Measurements & 3D extent',
    'sub.measNote': 'Canonical storage is square metres — originals are preserved. Example: 1,245 sq ft ≈ 115.66 m².',
    'sub.owner': 'Ownership / rights',
    'sub.ownerNote': 'Ownership information submitted by the user requires verification against authoritative records. Neither this form nor any AI output establishes legal ownership.',
    'sub.docs': 'Documents & evidence',
    'sub.docsOpt': '(optional — provide if available)',
    'sub.uploadDoc': 'Upload document',
    'sub.uploaded': 'Document uploaded',
    'sub.uploadFail': 'Upload failed: {e}',
    'sub.existing': 'Existing vs submitted',
    'sub.dupNote': 'Possible existing property found — no automatic merge',
    'sub.errType': 'Property type is required',
    'sub.errParcel': 'Parcel, ULPIN/reference or unit is required',
    'sub.errOwner': 'Owner / rights holder name is required',
    'sub.errDept': 'Department is required for government submissions',
    'sub.errTarget': 'For an update, select an existing property (lookup or map)',
    'sub.lookupFail': 'Lookup failed: {e}',
    'sub.mapApplied': 'Map selection applied to the form',
    'sub.mapPick': 'Pick a parcel or building on the map',
    'sub.demoFilled': 'Demo data filled — click Continue through the steps to showcase',
    'sub.closeMap': 'Close',
    'sub.mapHelp': 'Click a parcel or building to auto-fill the form',
    'sub.mapTitle': 'Select property on map',
    // track
    'trk.title': 'My Submissions',
    'trk.sub': 'Track every property submission and its verification timeline',
    'trk.new': '+ New submission',
    'trk.empty': 'No submissions yet. Start one from the submission form.',
    'trk.loading': 'Loading submission…',
    'trk.notfound': 'Submission not found or not shared with you.',
    'trk.trust': 'Trust: ',
    'trk.authorized': 'Authorized department',
    'trk.correction': 'Correction required',
    'trk.editResub': 'Edit & resubmit',
    'trk.continue': 'Continue editing draft',
    'trk.data': 'Submitted data',
    'trk.docs': 'Documents ({n})',
    'trk.download': '· download',
    'trk.dlFail': 'Download failed',
    'trk.timeline': 'Timeline',
    'trk.awaiting': 'Awaiting first review.',
    // queue
    'q.title': 'Property Verification Queue',
    'q.sub': 'Citizen submissions awaiting human verification — data is unverified until you act',
    'q.newActive': 'New + active',
    'q.new': 'New',
    'q.under': 'Under Review',
    'q.field': 'Field Check',
    'q.corr': 'Correction Required',
    'q.empty': 'Queue is clear. New citizen submissions will appear here.',
    'q.high': 'HIGH PRIORITY',
    'q.open': 'Open workspace',
    'q.opening': 'Opening workspace…',
    'q.notfound': 'Submission not found.',
    'q.subInfo': 'Submitted information',
    'q.unverified': '(unverified claim)',
    'q.existing': 'Existing cadastral record',
    'q.authoritative': '(authoritative)',
    'q.loadLinked': 'Load linked record',
    'q.noLinked': 'No linked existing record',
    'q.notFoundRec': 'Existing record not found: {e}',
    'q.viewMap': 'View on 2D Map',
    'q.open3d': 'Open 3D Building',
    'q.locPreview': 'Location preview — this property only',
    'q.noLoc': 'No location linked yet — pick via lookup or map in the submission.',
    'q.prior': 'Prior actions: ',
    'q.decision': 'Decision',
    'q.reason': 'Reason / officer note * Required for approve, reject, correction',
    'q.reasonPh': 'Evidence-based justification…',
    'q.needReason': 'A reason is required',
    'q.start': 'Start verification',
    'q.approve': 'Approve → integrate',
    'q.reject': 'Reject',
    'q.approved': 'Approved — live record updated ({n} changes)',
    'q.actionFail': 'Action failed: {e}',
    'q.corrFields': 'Fields requiring correction:',
    'q.reqCorr': 'Request correction',
    'q.fieldT': 'Field verification',
    'q.fieldOpen': 'open',
    'q.fieldHelp': 'Assign a site visit to a surveyor. They complete it from Field Work — your approval here is still the final decision. Demo account username is surveyor',
    'q.assignee': 'Assign surveyor (username) — use “surveyor” for demo',
    'q.scheduled': 'Scheduled',
    'q.fReason': 'Reason',
    'q.fReasonPh': 'Why a site visit is needed',
    'q.createReq': 'Create field request',
    'q.assigned': 'Field verification {v} assigned to {a} — visible in Field Work',
    'q.reqFail': 'Field request failed: {e}',
    'q.completed': 'Completed',
    'q.by': 'by {v}',
    'q.viewField': 'View field record',
    'q.openNote': '— surveyor records result from Field Work (officer may also submit here)',
    'q.obs': 'Observed (JSON: coords, area, height…)',
    'q.notes': 'Notes',
    'q.badJson': 'Observed JSON is invalid',
    'q.resultOk': 'Field result recorded → {v}',
    'q.resultFail': 'Result failed: {e}',
    'q.submitResult': 'Submit result',
    'q.docs': 'Documents ({n})',
    'q.docOpen': '· open',
    'q.noDocs': 'No documents attached.',
    // field work
    'fw.title': 'My Field Work',
    'fw.titleAll': 'Field Verifications',
    'fw.sub': 'All open site visits — assigned to you or open pool. Open one and submit; it auto-claims to you. Officers take the final decision.',
    'fw.subAll': 'All field verification requests — assign to surveyors, track recommendations.',
    'fw.openClosed': 'Open + completed',
    'fw.openOnly': 'Open only',
    'fw.doneOnly': 'Completed',
    'fw.empty': 'No field visits yet. Officers create them from the Verification Queue → Open workspace → Field verification.',
    'fw.emptyAll': 'No field verification requests yet. Create one from a submission in the Verification Queue.',
    'fw.mine': 'Assigned to me ({n})',
    'fw.pool': 'Other open visits — claimable ({n})',
    'fw.poolNote': 'open pool — opening claims it to you',
    'fw.openWs': 'Open field workspace',
    'fw.assignHint': 'Assign new visits from Verification Queue → Open workspace → Field verification. Use username surveyor for the demo account.',
    'fw.opening': 'Opening field workspace…',
    'fw.notfound': 'Field verification not found.',
    'fw.visit': 'Field visit {v}',
    'fw.assignedTo': 'assigned to {a}',
    'fw.scheduled': 'scheduled {v}',
    'fw.officerNote': 'Officer instruction: {v}',
    'fw.doneRec': 'Completed with recommendation',
    'fw.doneNote': 'The submission is back with the officer for the final decision — no further edits.',
    'fw.what': 'What to verify',
    'fw.claim': '(officer claim — not yet authoritative)',
    'fw.claimed': 'Claimed measurements: ',
    'fw.evidence': 'Evidence documents ({n})',
    'fw.site': 'Site observation',
    'fw.siteH': 'Tick what you physically verified. Photographs + coordinates are mandatory for APPROVE.',
    'fw.fieldNotes': 'Field notes',
    'fw.fieldNotesPh': 'Access, occupancy, boundary markers, photos taken…',
    'fw.submitResult': 'Submit field result',
    'fw.resultNote': 'Result goes to the officer — APPROVE/REJECT here is a recommendation, not the final cadastral decision.',
    'fw.resultOk': 'Field result recorded → {v}',
    'fw.resultFail': 'Result failed: {e}',
    'fw.badJson': 'Observed JSON is invalid',
    'fw.noLoc': 'No location linked yet.',
    // map
    'map.searchPh': 'Search ULPIN / parcel / building / utility…',
    'map.search': 'Search',
    'map.parcels': 'Parcels',
    'map.buildings': 'Buildings',
    'map.under': 'Underground',
    'map.legend': 'Legend:',
    'map.verified': 'parcel verified',
    'map.review': 'parcel review',
    'map.building': 'building',
    'map.utility': 'utility',
    'map.selection': 'Selection',
    'map.loading': 'Loading details…',
    'map.hint': 'Click a building or parcel on the map. Demo flow: search Green Residency → click Building A → Open 3D View (2D→3D transition).',
    'map.open3d': 'Open 3D View →',
    'map.flow': 'Parcel → 3D tower → floors → units.',
    'map.showUnder': 'Show underground layer',
    'map.committed': 'Committed live: {p} parcels, {b} buildings, {u} utilities{s}. Marked Needs Review.',
    'map.skipped': ' · skipped {n} (already exist)',
    'map.commitFail': 'Commit failed: {e}',
    'map.discarded': 'Upload preview discarded — nothing was saved',
    'map.accept': 'Accept & commit',
    'map.committing': 'Committing…',
    'map.discard': 'Discard',
    // 3d viewer
    'v3d.exploded': 'Exploded view',
    'v3d.under': 'Underground mode',
    'v3d.reset': 'Reset view',
    'v3d.hint': 'Select floors vertically · click units on the highlighted floor.',
    'v3d.loadFail': 'Could not load this building. It may not exist — pick another tower above.',
    'v3d.isolated': 'Isolated view: {v}',
    'v3d.backTower': '← Back to tower',
    'v3d.loading': 'Loading building…',
    'v3d.loadFail2': 'Failed to load building. Check the backend and retry.',
    'v3d.pickFloor': 'Select a floor on the rail or in 3D.',
    'v3d.selected': 'Selected {v}',
    'v3d.showing': 'Showing {a} of {b} units · {c} rendered in 3D',
    'v3d.viewAll': 'View {v} in 3D → all rooms',
    'v3d.noUnits': 'No registered units on this floor (e.g. parking/lobby).',
    'v3d.pickUnit': 'Select a unit (e.g. 804 on F08) to see its 3D volume identity.',
    'v3d.protoNote': 'Prototype reference — NOT an official Govt. of India ULPIN.',
    'v3d.openIdentity': 'Open public digital identity →',
    'v3d.evLoading': 'Evidence loading…',
    'v3d.timeMachine': 'Time machine: 2024 registration → 2025 floor-plan update → 2026 LiDAR height check.',
    'v3d.scanNote': 'Scan → public property identity (safe fields only).',
    'v3d.report': 'Property Report (in-browser)',
    // ops: validation
    'val.title': 'Validation Center',
    'val.sub': 'AI-assisted topology checks — every finding needs human review',
    'val.run': 'Run validation engine',
    'val.done': 'Validation complete: {n} open issues',
    'val.fail': 'Review failed: {e}',
    'val.marked': 'Issue marked {v} — audit trail updated below',
    'val.loading': 'Loading issues…',
    'val.empty': 'No issues match these filters.',
    'val.allSev': 'All severities',
    'val.allSt': 'All statuses',
    'val.open': 'Open',
    'val.under': 'Under Review',
    'val.resolved': 'Resolved',
    'val.rejected': 'Rejected',
    'val.case': 'Case file →',
    'val.caseT': 'Case file',
    'val.caseS': 'One entity, full evidence story — snapshot, measurements, history, audit',
    'val.opening': 'Opening case file…',
    'val.noCase': 'No case file for this entity',
    'val.backCenter': 'Back to Validation Center',
    'val.regH': 'Registered height',
    'val.lidarH': 'LiDAR-derived height',
    'val.diff': 'Difference: ',
    'val.findings': 'Findings ({n})',
    'val.history': 'History',
    'val.audit': 'Live audit trail',
    'val.auditS': '(newest first — resolve above and watch it grow)',
    'val.noAudit': 'No audit rows yet for this entity — take an action above.',
    // ops: infra + reports + admin
    'inf.title': 'Underground Infrastructure',
    'inf.sub': 'Utility networks below the cadastre — depths, owners, affected parcels',
    'rep.title': 'Reports',
    'rep.sub': 'Officer-grade property, evidence and validation reports',
    'rep.type': 'Report type',
    'rep.prop': 'Property identity report',
    'rep.evidence': 'Evidence pack',
    'rep.valSum': 'Validation summary',
    'rep.generate': 'Generate',
    'rep.generating': 'Generating…',
    'rep.print': 'Print / PDF',
    'rep.csv': 'Export CSV',
    'rep.fail': 'Report failed: {e}',
    'rep.pick': 'Pick a report type and click Generate. Property and evidence reports need a valid ULPIN.',
    'rep.propT': 'Property Identity Report',
    'rep.evT': 'Evidence Pack — ',
    'rep.none': 'None.',
    'rep.custody': 'Chain of custody (history)',
    'adm.title': 'Administration',
    'adm.sub': 'Datasets, confidence rules, ingestion and audit',
    'adm.thresholds': 'Validation thresholds',
    'adm.proto': '(prototype rules)',
    'adm.bands': 'Score bands for the confidence ring and status labels. Backend defaults match these values.',
    'adm.saved': 'Confidence thresholds updated',
    'adm.ingest': 'Data ingestion',
    'adm.ingestS': '(prototype)',
    'adm.ingestD': 'Upload GeoJSON/JSON (validate → preview on map → accept & commit, or discard). Committed records go live as Needs Review. CSV/KML parsing is simulated in demo.',
    'adm.choose': 'Choose file…',
    'adm.validated': 'Import validated: {n} features {f} from {v}',
    'adm.importFail': 'Import failed: {e}',
    'adm.preview': 'Preview {n} features on map →',
    'adm.audit': 'Audit trail',
    'adm.filter': 'Filter user / action / entity…',
    'adm.noMatch': 'No audit rows match.',
    'adm.noEvents': 'No audit events yet — approve/resolve a validation issue to generate one.',
    'adm.roles': 'Roles: Public / anonymous (safe fields+QR) · Surveyor (inspect/upload) · Officer (approve/evidence/audit) · Admin (datasets/rules/analytics). Validation thresholds 95/80/60 are configurable prototype rules.',
    // copilot
    'ai.title': 'Cadastral Copilot',
    'ai.sub': 'AI-assisted · requires official verification',
    'ai.ph': 'Ask about parcels, floors, conflicts, utilities…',
    'ai.hint': 'Answers highlight matching objects on the map.',
    'ai.clear': 'Clear {n} map highlight(s)',
    'ai.results': 'Results: {n}',
    'ai.shown': '· shown on map',
    'ai.querying': 'Querying cadastral database…',
    'ai.hideS': 'Hide suggestions',
    'ai.showS': 'Show suggestions',
    'ai.down': 'Copilot is unreachable (demo fallback). …',
    'ai.llm': 'Mistral AI',
    'ai.rules': 'Rule-based',
    // tour
    'meta.DRAFT': 'Draft',
    'meta.DRAFTd': 'Not submitted yet.',
    'meta.PENDING': 'Pending Verification',
    'meta.PENDINGd': 'Awaiting officer review.',
    'meta.UNDER': 'Under Verification',
    'meta.UNDERd': 'An officer is reviewing it.',
    'meta.FIELD': 'Field Check',
    'meta.FIELDd': 'Surveyor field verification in progress.',
    'meta.CORR': 'Correction Required',
    'meta.CORRd': 'Please fix the flagged fields and resubmit.',
    'meta.APPROVED': 'Approved',
    'meta.APPROVEDd': 'Verified and accepted.',
    'meta.REJECTED': 'Rejected',
    'meta.REJECTEDd': 'Not accepted. Kept in history.',
    'meta.INTEGRATED': 'Integrated',
    'meta.INTEGRATEDd': 'Live in the cadastral system.',
    'meta.NEEDS': 'Needs Review',
    'meta.NEEDSd': 'Technical inconsistencies found.',
    // submit wizard: banners, fields, review rows
    'sub.survBanner': 'Surveyor workspace: file authenticated department data below, and complete site visits from Field Work. You do not file as a property owner — owner claims come from citizens and are assigned to you for verification.',
    'sub.req': '* Required',
    'sub.opt': 'Optional',
    'sub.cantDraft': 'Cannot open draft: {e}',
    'sub.mapPickFail': 'Map pick failed: {e}',
    'sub.contFail': 'Continue failed: {e}',
    'sub.chooseFile': 'Choose a file first',
    'sub.canon': '≈ {v} m² (canonical)',
    'sub.diffArea': 'Area',
    'sub.diffHeight': 'Building height',
    'sub.diffVert': 'Vertical range',
    'sub.subId': 'Submission {v}',
    'sub.source': 'Submission source',
    'sub.govtAs': 'Government / Department submission as',
    'sub.deptSrcSuffix': '. Source is recorded as an authorized institutional source.',
    'sub.deptName': 'Department name',
    'sub.fDept': 'Department',
    'sub.fDeptH': 'e.g. Survey Department, Municipal Property Cell',
    'sub.fPropNameH': 'e.g. Green Residency — A804',
    'sub.fExistUlpH': 'If updating a known record',
    'sub.fUsageH': 'Residential, commercial, office…',
    'sub.fBoundaryH': 'Survey, GIS, manual…',
    'sub.fFloorNoH': 'Integer; -2/-1 basements, 0 ground',
    'sub.fUnitTypeH': '2BHK, shop, office, parking bay…',
    'sub.fAffParcelsH': 'Comma-separated parcel IDs',
    'sub.fLatH': 'Decimal degrees',
    'sub.fOwnerPh': 'As per supporting document',
    'sub.fShareH': 'e.g. 50% for joint holding',
    'sub.fFileH': 'PDF / image, 10 MB max',
    'sub.fSurvey': 'Survey number',
    'sub.fSubdiv': 'Sub-division number',
    'sub.fPlot': 'Plot number',
    'sub.fTower': 'Tower / Block',
    'sub.fUsage': 'Property usage',
    'sub.fParcelID': 'Parcel ID',
    'sub.fLandUse': 'Land use',
    'sub.fBoundary': 'Boundary source',
    'sub.fBldName': 'Building name',
    'sub.fBldId': 'Building ID',
    'sub.fBldType': 'Building type',
    'sub.fFloors': 'Number of floors',
    'sub.fBasements': 'Basements',
    'sub.fConstYr': 'Construction year',
    'sub.fApprRef': 'Building approval ref',
    'sub.fComplete': 'Completion / occupancy',
    'sub.fFloorNo': 'Floor number',
    'sub.fFloorUse': 'Floor usage',
    'sub.fFloorPlan': 'Floor plan available',
    'sub.yes': 'Yes',
    'sub.no': 'No',
    'sub.fUnitNo': 'Unit / flat number',
    'sub.fUnitType': 'Unit type',
    'sub.fUtilType': 'Utility type',
    'sub.fDepth': 'Depth (m, negative)',
    'sub.fInstYr': 'Installation year',
    'sub.fAffParcels': 'Affected parcels',
    'sub.fState': 'State',
    'sub.fDistrict': 'District',
    'sub.fTehsil': 'Sub-District / Tehsil',
    'sub.fCity': 'City / Town / Village',
    'sub.fWard': 'Ward',
    'sub.fLocality': 'Locality',
    'sub.fColony': 'Colony / Society',
    'sub.fStreet': 'Street / Road',
    'sub.fPin': 'PIN Code',
    'sub.fLandmark': 'Landmark',
    'sub.fLat': 'Latitude',
    'sub.fLng': 'Longitude',
    'sub.fCoordSrc': 'Coordinate source',
    'sub.fAcc': 'Accuracy (m)',
    'sub.fSurveyDate': 'Survey date',
    'sub.mLength': 'Length (m)',
    'sub.mWidth': 'Width (m)',
    'sub.mHeight': 'Height (m)',
    'sub.mDepth': 'Depth (m)',
    'sub.mPerim': 'Perimeter (m)',
    'sub.mBldH': 'Building height (m)',
    'sub.mFloorH': 'Floor height (m)',
    'sub.mBaseDepth': 'Basement depth (m)',
    'sub.mGround': 'Ground elevation (m)',
    'sub.mZmin': 'Z-Min (m)',
    'sub.mZmax': 'Z-Max (m)',
    'sub.mElevSrc': 'Elevation source',
    'sub.vertExt': 'Vertical extent: {v} m',
    'sub.fOwner': 'Owner / rights holder',
    'sub.fOwnerRef': 'Ownership reference',
    'sub.fOwnerType': 'Ownership type',
    'sub.fRightType': 'Right type',
    'sub.fRegRef': 'Registration reference',
    'sub.fShare': 'Ownership share',
    'sub.fLeaseNotes': 'Lease / easement notes',
    'sub.fDocType': 'Document type',
    'sub.fFile': 'File',
    'sub.fDocNo': 'Document number',
    'sub.fDocDate': 'Document date',
    'sub.fAuthority': 'Issuing authority',
    'sub.fDesc': 'Description',
    'sub.rProp': 'Property',
    'sub.rIntent': 'Intent',
    'sub.rParcel': 'Parcel',
    'sub.rBld': 'Building',
    'sub.rFloor': 'Floor',
    'sub.rUnit': 'Unit',
    'sub.rArea': 'Area',
    'sub.rVert': 'Vertical',
    'sub.rOwner': 'Owner (claim)',
    'sub.rDocs': 'Documents',
    'sub.rSource': 'Source',
    'sub.rStatus': 'Status on submit',
    'sub.rNew': 'Register new',
    'sub.rUpd': 'Update existing',
    'sub.rUploaded': 'uploaded',
    'sub.rDept': 'Authorized department ({v})',
    'sub.rOwnerUnv': 'Property owner (unverified)',
    'sub.rValInt': 'Validate → Integrated / Needs Review',
    'sub.rPendHum': 'Pending human verification',
    'sub.aiAssist': 'AI assist: {v}',
    'sub.ownerClaim': 'Property Owner / Citizen submission. Your information is a claim until verified — an officer reviews it before it becomes cadastral data.',
    // track rows
    'trk.newReg': 'new registration',
    'trk.upd': 'update',
    'trk.fields': 'Fields: {v}',
    'trk.meas': 'Measurements:',
    'trk.rSurvey': 'Survey',
    'trk.rAddr': 'Address',
    'trk.rCoords': 'Coords',
    'trk.rRight': 'Right',
    // queue rows + checks
    'q.aria': 'Queue filter',
    'q.subStatus': 'Submission {v}',
    'q.meas': 'Measurements:',
    'q.claimed': 'Claimed: {v}',
    'q.openField': 'Open field record',
    'q.c1': 'Property exists',
    'q.c2': 'Address matches',
    'q.c3': 'Parcel boundary matches',
    'q.c4': 'Building exists',
    'q.c5': 'Floor exists',
    'q.c6': 'Unit exists',
    'q.c7': 'Measurements verified',
    'q.c8': 'Coordinates checked',
    'q.c9': 'Documents checked',
    'q.c10': 'Photographs collected',
    // field work fragments
    'fw.you': '(you)',
    'fw.ariaStatus': 'Status filter',
    // map drawer
    'map.utilNotFound': 'Utility not found',
    'map.loadFail': 'Failed to load details',
    'map.prevTitle': 'Preview: {v}',
    'map.prevSub': '{n} features · dashed cyan · not saved yet',
    'map.floors': 'Floors',
    'map.height': 'Height',
    'map.conf': 'Confidence',
    'map.parcelX': 'Parcel {v}',
    'map.affParcels': 'Affected parcels: {v}',
    'map.blds': 'Buildings ({n})',
    'map.flConf': '{f} floors · {c}%',
    'map.underX': '{n} underground assets intersect this parcel: {v}',
    'map.sqft': 'sq.ft',
    // 3d info rows
    'v3d.crumbDash': 'Dashboard',
    'v3d.crumbMap': 'Map',
    'v3d.resetCam': 'Reset camera',
    'v3d.legend': 'Legend:',
    'v3d.lSlab': 'floor slab',
    'v3d.lRooms': 'rooms (tags show numbers)',
    'v3d.lUnv': 'unverified room',
    'v3d.lSel': 'selected room · click a room/tag',
    'v3d.lSelF': 'selected floor',
    'v3d.lVer': 'verified',
    'v3d.lRev': 'review',
    'v3d.lBase': 'basement',
    'v3d.lUnits': 'units',
    'v3d.lSelU': 'selected unit · drag to orbit · scroll to zoom · click floor/unit',
    'v3d.underNote': 'Underground view: water / electrical / sewer / telecom / gas / metro tubes below the ground plane (ground semi-transparent).',
    'v3d.proto': 'Prototype 3D ULPIN:',
    'v3d.iid': 'Internal ID:',
    'v3d.rParcel': 'Parcel:',
    'v3d.rFloor': 'Floor:',
    'v3d.rArea': 'Area:',
    'v3d.rVert': 'Vertical:',
    'v3d.rType': 'Type:',
    'v3d.rOwner': 'Owner:',
    'v3d.missing': '— missing',
    'v3d.towerRail': '— tower rail',
    // ops report/admin rows
    'rep.bySev': 'By severity:',
    'rep.bySt': 'By status:',
    'rep.valSumN': 'Validation Summary — {n} open issues',
    'val.page': '{n} issues · page {p}',
    'adm.sParcels': 'Parcels',
    'adm.sBld': 'Buildings',
    'adm.sUnits': 'Units',
    'adm.sOpen': 'Open issues',
    'adm.sUtils': 'Utilities',
    'adm.sVer': 'Verified units',
    'adm.sNeeds': 'Needs review',
    'adm.sAvg': 'Avg confidence',
    'adm.verifiedGe': 'Verified ≥',
    'adm.highGe': 'High ≥',
    'adm.revGe': 'Review ≥',
    'adm.saveBtn': 'Save',
    'adm.allOpt': 'All',
    'adm.last': 'Last: {v}',
    'adm.feat': 'features',
    'adm.bbox': 'bbox {v}',
    // copilot + tour fragments + dashboard aria
    'ai.conf': '· AI confidence {v}%',
    'ai.close': 'Close copilot',
    'ai.ask': 'Ask the copilot',
    'ai.send': 'Send question',
    'tour.copilotHi': 'Copilot: {n} height mismatches highlighted',
    'tour.copilotDown': 'Copilot unavailable: {e}',
    'tour.autoT': 'Toggle auto-play',
    'tour.endT': 'End tour',
    'dash.scaleAria': 'Number scale',
    'sub.fExistUlp': 'Existing ULPIN / reference',
    'sub.fUtil': 'Underground asset',
    'q.rUlp': 'ULPIN ref',
    'q.rPlot': 'Plot',
    'q.rFloors': 'Floors',
    'q.rUsage': 'Usage',
    'q.rHeight': 'Height',
    'q.existArea': 'Area {a} sq.ft · z {zmin}–{zmax} m · {s} · {c}%',
    'rep.rStatus': 'Status',
    'rep.rConf': 'Confidence',
    'rep.rOwner': 'Owner',
    'rep.rType': 'Type',
    'rep.missing': '— missing',
    'val.sevAria': 'Severity filter',
    'val.stAria': 'Status filter',
    'v3d.parcelAssets': ' Parcel {p} → {n} intersecting asset(s) ({v}).',
    'v3d.repUlp': 'ULPIN:',
    'v3d.repParcel': 'Parcel {p} · {b} · {f} · Unit {u}',
    'v3d.repArea': 'Area {a} sq.ft · z {z}m · {s} · {c}%',
    'v3d.repOwner': 'Owner: {v} ({r})',
    'tour.guided': 'GUIDED DEMO',
    'tour.back': 'Back',
    'tour.next': 'Next',
    'tour.finish': 'Finish tour',
    'tour.skip': 'Skip tour',
    'tour.auto': 'Auto-play (9s/step)',
    'tour.pause': 'Pause auto-play',
  },
  hi: {
    'dash.load': 'स्टाफ डैशबोर्ड लोड हो रहा है…',
    'dash.err': 'आंकड़े लोड नहीं हो सके।',
    'dash.title': 'स्टाफ डैशबोर्ड',
    'dash.sub': '· अधिकारियों / सर्वेक्षकों / प्रशासकों हेतु परिचालन रजिस्टर। नागरिक सेवा पोर्टल प्रयोग करें।',
    'dash.portal': 'सेवा पोर्टल →',
    'dash.glance': 'एक नज़र में',
    'dash.liveNote': 'लाइव डेमो डेटासेट — प्रत्येक संख्या नीचे का वास्तविक अभिलेख है',
    'dash.cityNote': 'सचित्र शहर-स्तरीय रजिस्टर — वास्तविक अभिलेखों हेतु लाइव डेमो पर जाएं',
    'dash.city': 'शहर स्तर',
    'dash.live': 'लाइव डेमो',
    'dash.parcels': 'कुल पार्सल',
    'dash.buildings': 'कुल भवन',
    'dash.units': 'पंजीकृत इकाइयां',
    'dash.verified': 'सत्यापित',
    'dash.needs': 'समीक्षा आवश्यक',
    'dash.spatial': 'स्थानिक विवाद',
    'dash.owner': 'स्वामित्व विवाद',
    'dash.under': 'भूमिगत संपत्तियां',
    'dash.avg': 'औसत विश्वास',
    'dash.flag': 'फ्लैगशिप डेमो: ग्रीन रेजीडेंसी',
    'dash.flagS': '3 टावर · 12/10/15 मंज़िल · B1/B2',
    'dash.openMap': 'मानचित्र खोलें',
    'dash.open3d': '3D खोलें',
    'dash.quality': 'स्थानिक गुणवत्ता',
    'dash.qualityS': 'लाइव डेमो सत्यापन संकेत',
    'dash.sev': 'गंभीरता अनुसार खुली समस्याएं',
    'dash.mix': 'सत्यापन मिश्रण (डेमो)',
    'dash.needsR': 'समीक्षा आवश्यक',
    'dash.intake': 'आवेदन प्राप्ति',
    'dash.intakeS': 'भू-मानचित्र में आता संपत्ति डेटा',
    'dash.total': 'कुल',
    'dash.pending': 'सत्यापन लंबित',
    'dash.citizen': 'नागरिक',
    'dash.govt': 'सरकार',
    'dash.myField': 'मेरा क्षेत्र कार्य',
    'dash.field': 'क्षेत्र कार्य',
    'dash.fieldS': 'आपको सौंपे गए स्थल भ्रमण',
    'dash.fieldAll': 'क्षेत्र सत्यापन कार्यभार',
    'dash.openV': 'खुले भ्रमण',
    'dash.doneV': 'पूर्ण',
    'dash.myFilings': 'मेरी विभागीय प्रविष्टियां',
    'dash.startFiling': 'सरकारी प्रविष्टि शुरू करें',
    'dash.siteReq': 'स्थल भ्रमण आवश्यक',
    'dash.openArrow': 'खोलें →',
    'dash.attn': 'ध्यान आवश्यक',
    'dash.attnS': 'नवीनतम सत्यापन निष्कर्ष — सत्यापन केंद्र में देखें',
    'dash.noIssues': 'कोई खुली समस्या नहीं।',
    'sub.title': 'संपत्ति डेटा जमा करना',
    'sub.sub': '3D भू-मानचित्र प्रणाली में एकीकरण हेतु संपत्ति जानकारी जमा या अद्यतन करें।',
    'sub.ownerCard': 'संपत्ति स्वामी / नागरिक',
    'sub.ownerD': 'अपनी संपत्ति जानकारी जमा या अद्यतन करें। सत्यापित भू-जानकारी बनने से पहले नागरिक आवेदनों की अधिकृत सरकारी अधिकारी समीक्षा करता है।',
    'sub.govtCard': 'सरकार / अधिकृत विभाग',
    'sub.govtD': 'अधिकृत विभाग से प्रमाणित संपत्ति, भूमि, भवन, अवसंरचना या स्थानिक जानकारी जमा करें।',
    'sub.govtNote': 'अधिकृत स्रोत: स्वचालित तकनीकी मान्यता, कोई नागरिक सत्यापन कतार नहीं।',
    'sub.asOwner': 'संपत्ति स्वामी के रूप में जमा करें',
    'sub.asGovt': 'सरकारी विभाग के रूप में जमा करें',
    'sub.needCitizen': 'संपत्ति स्वामी के रूप में जमा हेतु citizen (demo123) से साइन इन करें।',
    'sub.needGovt': 'अधिकारी, सर्वेक्षक या प्रशासक खाता आवश्यक।',
    'sub.mySubs': 'मेरे आवेदन',
    'sub.myField': 'मेरा क्षेत्र कार्य',
    'sub.queue': 'सत्यापन कतार',
    'sub.allField': 'समस्त क्षेत्र कार्य',
    'sub.flow': 'प्रवाह: आवेदन → स्वचालित मान्यता → मानव सत्यापन → अनुमोदन → लाइव अभिलेख।',
    'sub.needsAuth': 'संपत्ति आवेदन हेतु नागरिक या सरकारी खाता चाहिए। आगे बढ़ने हेतु citizen (demo123) से साइन इन करें।',
    'sub.opening': 'ड्राफ्ट खुल रहा है…',
    'sub.success': 'आवेदन सफल',
    'sub.govtDone': 'अधिकृत विभागीय स्रोत दर्ज। स्वचालित मान्यता चली; अभिलेख एकीकृत या समीक्षा हेतु चिह्नित है — नागरिक कतार में कभी नहीं।',
    'sub.ownerDone': 'आपकी संपत्ति जानकारी सफलतापूर्वक जमा हो गई। सत्यापित भू-डेटा बनने से पहले अधिकृत अधिकारी इसका सत्यापन करेगा।',
    'sub.track': 'आवेदन ट्रैक करें',
    'sub.newHead': 'नया संपत्ति आवेदन',
    'sub.govtMode': 'अधिकृत विभागीय स्रोत — स्वचालित मान्यता, कोई नागरिक कतार नहीं।',
    'sub.ownerMode': 'स्वामी आवेदन — भू-डेटा बनने से पहले मानव सत्यापन आवश्यक।',
    'sub.fillDemo': 'डेमो डेटा भरें',
    'sub.fillTitle': 'प्रदर्शन हेतु पूरा फ़ॉर्म डेमो डेटा से भरें',
    'sub.saveDraft': 'ड्राफ्ट सहेजें',
    'sub.saved': 'ड्राफ्ट सहेजा गया',
    'sub.saveFail': 'सहेजना विफल: {e}',
    'sub.back': 'पीछे',
    'sub.continue': 'आगे बढ़ें',
    'sub.submitBtn': 'संपत्ति डेटा जमा करें',
    'sub.submitFail': 'जमा करना विफल: {e}',
    'sub.declare': 'कृपया घोषणा स्वीकार करें',
    'sub.review': 'समीक्षा व घोषणा',
    'sub.declare1': 'मैं घोषणा करता/करती हूं कि जानकारी मेरी जानकारी में सत्य है। मैं समझता/समझती हूं कि',
    'sub.declareGovt': 'तकनीकी मान्यता के बाद यह अधिकृत विभागीय स्रोत के रूप में दर्ज होगा।',
    'sub.declareOwner': 'स्वामित्व विवरण सत्यापन लंबित दावे हैं और कानूनी स्वामित्व स्थापित नहीं करते।',
    'sub.what': 'आप क्या करना चाहते हैं?',
    'sub.newKind': 'नई संपत्ति पंजीकृत / जमा करें',
    'sub.newKindD': 'इस संपत्ति हेतु पहली बार प्रविष्टि',
    'sub.updKind': 'मौजूदा संपत्ति अद्यतन करें',
    'sub.updKindD': 'सिस्टम में मौजूद अभिलेख सुधारें या बढ़ाएं',
    'sub.find': 'मौजूदा संपत्ति खोजें',
    'sub.findH': 'ULPIN, पार्सल, भवन, इकाई, सर्वे नं. या पता — वैश्विक खोज का पुनः प्रयोग',
    'sub.pickMap': 'मानचित्र पर संपत्ति चुनें',
    'sub.linked': 'लिंक्ड: {v}',
    'sub.propLoc': 'संपत्ति व स्थान',
    'sub.propType': 'संपत्ति प्रकार',
    'sub.propName': 'संपत्ति नाम',
    'sub.parcel': 'पार्सल',
    'sub.parcelId': 'पार्सल ID',
    'sub.building': 'भवन',
    'sub.floor': 'तल',
    'sub.unit': 'अपार्टमेंट / इकाई',
    'sub.addr': 'पता व निर्देशांक',
    'sub.pickLoc': 'मानचित्र पर स्थान चुनें',
    'sub.meas': 'माप व 3D विस्तार',
    'sub.measNote': 'मानक भंडारण वर्ग मीटर में है — मूल मान सुरक्षित रहते हैं। उदाहरण: 1,245 वर्ग फुट ≈ 115.66 वर्ग मी.।',
    'sub.owner': 'स्वामित्व / अधिकार',
    'sub.ownerNote': 'उपयोगकर्ता द्वारा प्रस्तुत स्वामित्व जानकारी का आधिकारिक अभिलेखों से सत्यापन आवश्यक है। न यह फ़ॉर्म, न कोई AI आउटपुट कानूनी स्वामित्व स्थापित करता है।',
    'sub.docs': 'दस्तावेज़ व साक्ष्य',
    'sub.docsOpt': '(वैकल्पिक — उपलब्ध हो तो दें)',
    'sub.uploadDoc': 'दस्तावेज़ अपलोड करें',
    'sub.uploaded': 'दस्तावेज़ अपलोड हुआ',
    'sub.uploadFail': 'अपलोड विफल: {e}',
    'sub.existing': 'मौजूदा बनाम प्रस्तुत',
    'sub.dupNote': 'संभावित मौजूदा संपत्ति मिली — कोई स्वचालित विलय नहीं',
    'sub.errType': 'संपत्ति प्रकार आवश्यक है',
    'sub.errParcel': 'पार्सल, ULPIN/संदर्भ या इकाई आवश्यक है',
    'sub.errOwner': 'स्वामी / अधिकार धारक का नाम आवश्यक है',
    'sub.errDept': 'सरकारी आवेदनों हेतु विभाग आवश्यक है',
    'sub.errTarget': 'अद्यतन हेतु मौजूदा संपत्ति चुनें (लुकअप या मानचित्र)',
    'sub.lookupFail': 'लुकअप विफल: {e}',
    'sub.mapApplied': 'मानचित्र चयन फ़ॉर्म में लागू हुआ',
    'sub.mapPick': 'मानचित्र पर पार्सल या भवन चुनें',
    'sub.demoFilled': 'डेमो डेटा भरा गया — प्रदर्शन हेतु चरणों में आगे बढ़ें',
    'sub.closeMap': 'बंद करें',
    'sub.mapHelp': 'फ़ॉर्म स्वतः भरने हेतु पार्सल या भवन पर क्लिक करें',
    'sub.mapTitle': 'मानचित्र पर संपत्ति चुनें',
    'trk.title': 'मेरे आवेदन',
    'trk.sub': 'प्रत्येक संपत्ति आवेदन व उसकी सत्यापन टाइमलाइन ट्रैक करें',
    'trk.new': '+ नया आवेदन',
    'trk.empty': 'अभी कोई आवेदन नहीं। आवेदन फ़ॉर्म से शुरू करें।',
    'trk.loading': 'आवेदन लोड हो रहा है…',
    'trk.notfound': 'आवेदन नहीं मिला या आपके साथ साझा नहीं है।',
    'trk.trust': 'विश्वास: ',
    'trk.authorized': 'अधिकृत विभाग',
    'trk.correction': 'सुधार आवश्यक',
    'trk.editResub': 'संपादित कर पुनः जमा करें',
    'trk.continue': 'ड्राफ्ट संपादन जारी रखें',
    'trk.data': 'प्रस्तुत डेटा',
    'trk.docs': 'दस्तावेज़ ({n})',
    'trk.download': '· डाउनलोड',
    'trk.dlFail': 'डाउनलोड विफल',
    'trk.timeline': 'टाइमलाइन',
    'trk.awaiting': 'प्रथम समीक्षा की प्रतीक्षा।',
    'q.title': 'संपत्ति सत्यापन कतार',
    'q.sub': 'मानव सत्यापन प्रतीक्षारत नागरिक आवेदन — आपके कार्य तक डेटा असत्यापित है',
    'q.newActive': 'नए + सक्रिय',
    'q.new': 'नए',
    'q.under': 'समीक्षाधीन',
    'q.field': 'क्षेत्र जांच',
    'q.corr': 'सुधार आवश्यक',
    'q.empty': 'कतार खाली है। नए नागरिक आवेदन यहां दिखेंगे।',
    'q.high': 'उच्च प्राथमिकता',
    'q.open': 'कार्यक्षेत्र खोलें',
    'q.opening': 'कार्यक्षेत्र खुल रहा है…',
    'q.notfound': 'आवेदन नहीं मिला।',
    'q.subInfo': 'प्रस्तुत जानकारी',
    'q.unverified': '(असत्यापित दावा)',
    'q.existing': 'मौजूदा भू-अभिलेख',
    'q.authoritative': '(आधिकारिक)',
    'q.loadLinked': 'लिंक्ड अभिलेख लोड करें',
    'q.noLinked': 'कोई लिंक्ड मौजूदा अभिलेख नहीं',
    'q.notFoundRec': 'मौजूदा अभिलेख नहीं मिला: {e}',
    'q.viewMap': '2D मानचित्र पर देखें',
    'q.open3d': '3D भवन खोलें',
    'q.locPreview': 'स्थान पूर्वावलोकन — केवल यह संपत्ति',
    'q.noLoc': 'अभी कोई स्थान लिंक्ड नहीं — आवेदन में लुकअप या मानचित्र से चुनें।',
    'q.prior': 'पूर्व कार्रवाइयां: ',
    'q.decision': 'निर्णय',
    'q.reason': 'कारण / अधिकारी टिप्पणी * अनुमोदन, अस्वीकृति, सुधार हेतु आवश्यक',
    'q.reasonPh': 'साक्ष्य-आधारित औचित्य…',
    'q.needReason': 'कारण आवश्यक है',
    'q.start': 'सत्यापन शुरू करें',
    'q.approve': 'अनुमोदन → एकीकृत करें',
    'q.reject': 'अस्वीकार करें',
    'q.approved': 'अनुमोदित — लाइव अभिलेख अद्यतन ({n} परिवर्तन)',
    'q.actionFail': 'कार्रवाई विफल: {e}',
    'q.corrFields': 'सुधार आवश्यक फ़ील्ड:',
    'q.reqCorr': 'सुधार का अनुरोध करें',
    'q.fieldT': 'क्षेत्र सत्यापन',
    'q.fieldOpen': 'खुला',
    'q.fieldHelp': 'सर्वेक्षक को स्थल भ्रमण सौंपें। वे क्षेत्र कार्य से पूर्ण करते हैं — यहां आपका अनुमोदन ही अंतिम निर्णय है। डेमो खाता उपयोगकर्ता नाम है surveyor',
    'q.assignee': 'सर्वेक्षक सौंपें (उपयोगकर्ता नाम) — डेमो हेतु “surveyor” प्रयोग करें',
    'q.scheduled': 'निर्धारित',
    'q.fReason': 'कारण',
    'q.fReasonPh': 'स्थल भ्रमण क्यों आवश्यक है',
    'q.createReq': 'क्षेत्र अनुरोध बनाएं',
    'q.assigned': 'क्षेत्र सत्यापन {v} {a} को सौंपा गया — क्षेत्र कार्य में दृश्य',
    'q.reqFail': 'क्षेत्र अनुरोध विफल: {e}',
    'q.completed': 'पूर्ण',
    'q.by': '{v} द्वारा',
    'q.viewField': 'क्षेत्र अभिलेख देखें',
    'q.openNote': '— सर्वेक्षक क्षेत्र कार्य से परिणाम दर्ज करता है (अधिकारी भी यहां जमा कर सकता है)',
    'q.obs': 'प्रेक्षित (JSON: निर्देशांक, क्षेत्र, ऊंचाई…)',
    'q.notes': 'टिप्पणियां',
    'q.badJson': 'प्रेक्षित JSON अमान्य है',
    'q.resultOk': 'क्षेत्र परिणाम दर्ज → {v}',
    'q.resultFail': 'परिणाम विफल: {e}',
    'q.submitResult': 'परिणाम जमा करें',
    'q.docs': 'दस्तावेज़ ({n})',
    'q.docOpen': '· खोलें',
    'q.noDocs': 'कोई दस्तावेज़ संलग्न नहीं।',
    'fw.title': 'मेरा क्षेत्र कार्य',
    'fw.titleAll': 'क्षेत्र सत्यापन',
    'fw.sub': 'सभी खुले स्थल भ्रमण — आपको सौंपे गए या खुले पूल। खोलें और जमा करें; यह स्वतः आपको क्लेम होता है। अंतिम निर्णय अधिकारी लेता है।',
    'fw.subAll': 'सभी क्षेत्र सत्यापन अनुरोध — सर्वेक्षकों को सौंपें, सिफारिशें ट्रैक करें।',
    'fw.openClosed': 'खुले + पूर्ण',
    'fw.openOnly': 'केवल खुले',
    'fw.doneOnly': 'पूर्ण',
    'fw.empty': 'अभी कोई क्षेत्र भ्रमण नहीं। अधिकारी सत्यापन कतार → कार्यक्षेत्र खोलें → क्षेत्र सत्यापन से बनाते हैं।',
    'fw.emptyAll': 'अभी कोई क्षेत्र सत्यापन अनुरोध नहीं। सत्यापन कतार में आवेदन से बनाएं।',
    'fw.mine': 'मुझे सौंपे गए ({n})',
    'fw.pool': 'अन्य खुले भ्रमण — क्लेम योग्य ({n})',
    'fw.poolNote': 'खुला पूल — खोलने पर आपको क्लेम होता है',
    'fw.openWs': 'क्षेत्र कार्यक्षेत्र खोलें',
    'fw.assignHint': 'सत्यापन कतार → कार्यक्षेत्र खोलें → क्षेत्र सत्यापन से नए भ्रमण सौंपें। डेमो खाते हेतु surveyor उपयोगकर्ता नाम प्रयोग करें।',
    'fw.opening': 'क्षेत्र कार्यक्षेत्र खुल रहा है…',
    'fw.notfound': 'क्षेत्र सत्यापन नहीं मिला।',
    'fw.visit': 'क्षेत्र भ्रमण {v}',
    'fw.assignedTo': '{a} को सौंपा गया',
    'fw.scheduled': 'निर्धारित {v}',
    'fw.officerNote': 'अधिकारी निर्देश: {v}',
    'fw.doneRec': 'सिफारिश सहित पूर्ण',
    'fw.doneNote': 'आवेदन अंतिम निर्णय हेतु अधिकारी के पास वापस है — आगे कोई संपादन नहीं।',
    'fw.what': 'क्या सत्यापित करें',
    'fw.claim': '(अधिकारी दावा — अभी आधिकारिक नहीं)',
    'fw.claimed': 'दावाकृत माप: ',
    'fw.evidence': 'साक्ष्य दस्तावेज़ ({n})',
    'fw.site': 'स्थल प्रेक्षण',
    'fw.siteH': 'जो भौतिक रूप से सत्यापित किया उस पर टिक करें। APPROVE हेतु फोटो + निर्देशांक अनिवार्य।',
    'fw.fieldNotes': 'क्षेत्र टिप्पणियां',
    'fw.fieldNotesPh': 'पहुंच, अधिभोग, सीमा चिह्न, ली गई फोटो…',
    'fw.submitResult': 'क्षेत्र परिणाम जमा करें',
    'fw.resultNote': 'परिणाम अधिकारी को जाता है — यहां APPROVE/REJECT सिफारिश है, अंतिम भू-निर्णय नहीं।',
    'fw.resultOk': 'क्षेत्र परिणाम दर्ज → {v}',
    'fw.resultFail': 'परिणाम विफल: {e}',
    'fw.badJson': 'प्रेक्षित JSON अमान्य है',
    'fw.noLoc': 'अभी कोई स्थान लिंक्ड नहीं।',
    'map.searchPh': 'ULPIN / पार्सल / भवन / उपयोगिता खोजें…',
    'map.search': 'खोजें',
    'map.parcels': 'पार्सल',
    'map.buildings': 'भवन',
    'map.under': 'भूमिगत',
    'map.legend': 'संकेत:',
    'map.verified': 'पार्सल सत्यापित',
    'map.review': 'पार्सल समीक्षा',
    'map.building': 'भवन',
    'map.utility': 'उपयोगिता',
    'map.selection': 'चयन',
    'map.loading': 'विवरण लोड हो रहा है…',
    'map.hint': 'मानचित्र पर भवन या पार्सल पर क्लिक करें। डेमो प्रवाह: Green Residency खोजें → Building A पर क्लिक करें → 3D दृश्य खोलें (2D→3D)।',
    'map.open3d': '3D दृश्य खोलें →',
    'map.flow': 'पार्सल → 3D टावर → तल → इकाइयां।',
    'map.showUnder': 'भूमिगत परत दिखाएं',
    'map.committed': 'लाइव प्रतिबद्ध: {p} पार्सल, {b} भवन, {u} उपयोगिताएं{s}। समीक्षा आवश्यक के रूप में चिह्नित।',
    'map.skipped': ' · {n} छोड़े गए (मौजूद हैं)',
    'map.commitFail': 'प्रतिबद्धता विफल: {e}',
    'map.discarded': 'अपलोड पूर्वावलोकन छोड़ा गया — कुछ सहेजा नहीं गया',
    'map.accept': 'स्वीकार व प्रतिबद्ध करें',
    'map.committing': 'प्रतिबद्ध हो रहा है…',
    'map.discard': 'छोड़ें',
    'v3d.exploded': 'विस्फोटित दृश्य',
    'v3d.under': 'भूमिगत मोड',
    'v3d.reset': 'दृश्य रीसेट करें',
    'v3d.hint': 'तलों को लंबवत चुनें · हाइलाइट तल पर इकाइयों पर क्लिक करें।',
    'v3d.loadFail': 'यह भवन लोड नहीं हो सका। अस्तित्व में नहीं हो सकता — ऊपर अन्य टावर चुनें।',
    'v3d.isolated': 'पृथक दृश्य: {v}',
    'v3d.backTower': '← टावर पर वापस',
    'v3d.loading': 'भवन लोड हो रहा है…',
    'v3d.loadFail2': 'भवन लोड विफल। बैकएंड जांचकर पुनः प्रयास करें।',
    'v3d.pickFloor': 'रेल या 3D में तल चुनें।',
    'v3d.selected': 'चयनित {v}',
    'v3d.showing': '{b} में से {a} इकाइयां दिख रहीं · 3D में {c} रेंडर',
    'v3d.viewAll': '{v} को 3D में देखें → सभी कमरे',
    'v3d.noUnits': 'इस तल पर कोई पंजीकृत इकाई नहीं (जैसे पार्किंग/लॉबी)।',
    'v3d.pickUnit': '3D आयतन पहचान हेतु इकाई चुनें (जैसे F08 पर 804)।',
    'v3d.protoNote': 'प्रोटोटाइप संदर्भ — भारत सरकार का आधिकारिक ULPIN नहीं।',
    'v3d.openIdentity': 'सार्वजनिक डिजिटल पहचान खोलें →',
    'v3d.evLoading': 'साक्ष्य लोड हो रहा है…',
    'v3d.timeMachine': 'टाइम मशीन: 2024 पंजीकरण → 2025 फ्लोर-प्लान अद्यतन → 2026 LiDAR ऊंचाई जांच।',
    'v3d.scanNote': 'स्कैन करें → सार्वजनिक संपत्ति पहचान (केवल सुरक्षित फ़ील्ड)।',
    'v3d.report': 'संपत्ति रिपोर्ट (ब्राउज़र में)',
    'val.title': 'सत्यापन केंद्र',
    'val.sub': 'AI-सहायित टोपोलॉजी जांच — प्रत्येक निष्कर्ष हेतु मानव समीक्षा आवश्यक',
    'val.run': 'सत्यापन इंजन चलाएं',
    'val.done': 'सत्यापन पूर्ण: {n} खुली समस्याएं',
    'val.fail': 'समीक्षा विफल: {e}',
    'val.marked': 'समस्या {v} चिह्नित — ऑडिट ट्रेल नीचे अद्यतन',
    'val.loading': 'समस्याएं लोड हो रही हैं…',
    'val.empty': 'इन फ़िल्टरों से कोई समस्या नहीं।',
    'val.allSev': 'सभी गंभीरता',
    'val.allSt': 'सभी स्थितियां',
    'val.open': 'खुला',
    'val.under': 'समीक्षाधीन',
    'val.resolved': 'समाधानित',
    'val.rejected': 'अस्वीकृत',
    'val.case': 'केस फ़ाइल →',
    'val.caseT': 'केस फ़ाइल',
    'val.caseS': 'एक इकाई, पूर्ण साक्ष्य कथा — स्नैपशॉट, माप, इतिहास, ऑडिट',
    'val.opening': 'केस फ़ाइल खुल रही है…',
    'val.noCase': 'इस इकाई हेतु कोई केस फ़ाइल नहीं',
    'val.backCenter': 'सत्यापन केंद्र पर वापस',
    'val.regH': 'पंजीकृत ऊंचाई',
    'val.lidarH': 'LiDAR-व्युत्पन्न ऊंचाई',
    'val.diff': 'अंतर: ',
    'val.findings': 'निष्कर्ष ({n})',
    'val.history': 'इतिहास',
    'val.audit': 'लाइव ऑडिट ट्रेल',
    'val.auditS': '(नवीनतम पहले — ऊपर समाधान करें और बढ़ता देखें)',
    'val.noAudit': 'इस इकाई हेतु अभी कोई ऑडिट पंक्ति नहीं — ऊपर कोई कार्रवाई करें।',
    'inf.title': 'भूमिगत अवसंरचना',
    'inf.sub': 'भू-मानचित्र के नीचे उपयोगिता नेटवर्क — गहराई, स्वामी, प्रभावित पार्सल',
    'rep.title': 'रिपोर्ट',
    'rep.sub': 'अधिकारी-स्तरीय संपत्ति, साक्ष्य व सत्यापन रिपोर्ट',
    'rep.type': 'रिपोर्ट प्रकार',
    'rep.prop': 'संपत्ति पहचान रिपोर्ट',
    'rep.evidence': 'साक्ष्य पैक',
    'rep.valSum': 'सत्यापन सारांश',
    'rep.generate': 'बनाएं',
    'rep.generating': 'बन रहा है…',
    'rep.print': 'प्रिंट / PDF',
    'rep.csv': 'CSV निर्यात',
    'rep.fail': 'रिपोर्ट विफल: {e}',
    'rep.pick': 'रिपोर्ट प्रकार चुनकर बनाएं दबाएं। संपत्ति व साक्ष्य रिपोर्ट हेतु मान्य ULPIN चाहिए।',
    'rep.propT': 'संपत्ति पहचान रिपोर्ट',
    'rep.evT': 'साक्ष्य पैक — ',
    'rep.none': 'कोई नहीं।',
    'rep.custody': 'अभिरक्षा श्रृंखला (इतिहास)',
    'adm.title': 'प्रशासन',
    'adm.sub': 'डेटासेट, विश्वास नियम, अंतर्ग्रहण और ऑडिट',
    'adm.thresholds': 'सत्यापन सीमाएं',
    'adm.proto': '(प्रोटोटाइप नियम)',
    'adm.bands': 'विश्वास वलय व स्थिति लेबल हेतु स्कोर बैंड। बैकएंड डिफ़ॉल्ट इन्हीं मानों से मेल खाते हैं।',
    'adm.saved': 'विश्वास सीमाएं अद्यतन',
    'adm.ingest': 'डेटा अंतर्ग्रहण',
    'adm.ingestS': '(प्रोटोटाइप)',
    'adm.ingestD': 'GeoJSON/JSON अपलोड करें (मान्य करें → मानचित्र पर पूर्वावलोकन → स्वीकार व प्रतिबद्ध करें, या छोड़ें)। प्रतिबद्ध अभिलेख समीक्षा आवश्यक के रूप में लाइव होते हैं। डेमो में CSV/KML पार्सिंग अनुकरणीय है।',
    'adm.choose': 'फ़ाइल चुनें…',
    'adm.validated': 'आयात मान्य: {v} से {n} फ़ीचर {f}',
    'adm.importFail': 'आयात विफल: {e}',
    'adm.preview': '{n} फ़ीचर मानचित्र पर पूर्वावलोकन →',
    'adm.audit': 'ऑडिट ट्रेल',
    'adm.filter': 'उपयोगकर्ता / कार्रवाई / इकाई फ़िल्टर…',
    'adm.noMatch': 'कोई ऑडिट पंक्ति मेल नहीं खाती।',
    'adm.noEvents': 'अभी कोई ऑडिट घटना नहीं — उत्पन्न करने हेतु सत्यापन समस्या अनुमोदित/समाधानित करें।',
    'adm.roles': 'भूमिकाएं: सार्वजनिक / अनाम (सुरक्षित फ़ील्ड+QR) · सर्वेक्षक (निरीक्षण/अपलोड) · अधिकारी (अनुमोदन/साक्ष्य/ऑडिट) · प्रशासक (डेटासेट/नियम/विश्लेषण)। सत्यापन सीमाएं 95/80/60 विन्यास योग्य प्रोटोटाइप नियम हैं।',
    'ai.title': 'भू-अभिलेख सहायक',
    'ai.sub': 'AI-सहायित · आधिकारिक सत्यापन आवश्यक',
    'ai.ph': 'पार्सल, तल, विवाद, उपयोगिताओं के बारे में पूछें…',
    'ai.hint': 'उत्तर मानचित्र पर मेल खाती वस्तुओं को हाइलाइट करते हैं।',
    'ai.clear': '{n} मानचित्र हाइलाइट साफ़ करें',
    'ai.results': 'परिणाम: {n}',
    'ai.shown': '· मानचित्र पर दिख रहा',
    'ai.querying': 'भू-डेटाबेस से पूछताछ हो रही है…',
    'ai.hideS': 'सुझाव छिपाएं',
    'ai.showS': 'सुझाव दिखाएं',
    'ai.down': 'सहायक पहुंच से बाहर है (डेमो फॉलबैक)। …',
    'ai.llm': 'Mistral AI',
    'ai.rules': 'नियम-आधारित',
    'meta.DRAFT': 'ड्राफ्ट',
    'meta.DRAFTd': 'अभी जमा नहीं।',
    'meta.PENDING': 'सत्यापन लंबित',
    'meta.PENDINGd': 'अधिकारी समीक्षा की प्रतीक्षा।',
    'meta.UNDER': 'सत्यापन चल रहा',
    'meta.UNDERd': 'अधिकारी समीक्षा कर रहा है।',
    'meta.FIELD': 'क्षेत्र जांच',
    'meta.FIELDd': 'सर्वेक्षक क्षेत्र सत्यापन चल रहा।',
    'meta.CORR': 'सुधार आवश्यक',
    'meta.CORRd': 'चिह्नित फ़ील्ड सुधारकर पुनः जमा करें।',
    'meta.APPROVED': 'अनुमोदित',
    'meta.APPROVEDd': 'सत्यापित व स्वीकृत।',
    'meta.REJECTED': 'अस्वीकृत',
    'meta.REJECTEDd': 'स्वीकार नहीं। इतिहास में रखा गया।',
    'meta.INTEGRATED': 'एकीकृत',
    'meta.INTEGRATEDd': 'भू-प्रणाली में लाइव।',
    'meta.NEEDS': 'समीक्षा आवश्यक',
    'meta.NEEDSd': 'तकनीकी विसंगतियां मिलीं।',
    'sub.survBanner': 'सर्वेक्षक कार्यक्षेत्र: नीचे प्रमाणित विभागीय डेटा दर्ज करें और क्षेत्र कार्य से स्थल भ्रमण पूर्ण करें। आप संपत्ति स्वामी के रूप में दाखिल नहीं करते — स्वामी दावे नागरिकों से आते हैं और सत्यापन हेतु आपको सौंपे जाते हैं।',
    'sub.req': '* आवश्यक',
    'sub.opt': 'वैकल्पिक',
    'sub.cantDraft': 'ड्राफ्ट नहीं खुल सका: {e}',
    'sub.mapPickFail': 'मानचित्र चयन विफल: {e}',
    'sub.contFail': 'आगे बढ़ना विफल: {e}',
    'sub.chooseFile': 'पहले फ़ाइल चुनें',
    'sub.canon': '≈ {v} वर्ग मी. (मानक)',
    'sub.diffArea': 'क्षेत्र',
    'sub.diffHeight': 'भवन ऊंचाई',
    'sub.diffVert': 'ऊंचाई परास',
    'sub.subId': 'आवेदन {v}',
    'sub.source': 'आवेदन स्रोत',
    'sub.govtAs': 'सरकार / विभागीय प्रविष्टि के रूप में',
    'sub.deptSrcSuffix': '। स्रोत अधिकृत संस्थागत स्रोत के रूप में दर्ज है।',
    'sub.deptName': 'विभाग का नाम',
    'sub.fDept': 'विभाग',
    'sub.fDeptH': 'जैसे सर्वेक्षण विभाग, नगर संपत्ति प्रकोष्ठ',
    'sub.fPropNameH': 'जैसे ग्रीन रेजीडेंसी — A804',
    'sub.fExistUlpH': 'ज्ञात अभिलेख अद्यतन कर रहे हों तो',
    'sub.fUsageH': 'आवासीय, वाणिज्यिक, कार्यालय…',
    'sub.fBoundaryH': 'सर्वेक्षण, GIS, मैनुअल…',
    'sub.fFloorNoH': 'पूर्णांक; -2/-1 बेसमेंट, 0 भूतल',
    'sub.fUnitTypeH': '2BHK, दुकान, कार्यालय, पार्किंग बे…',
    'sub.fAffParcelsH': 'अल्पविराम-पृथक पार्सल ID',
    'sub.fLatH': 'दशमलव डिग्री',
    'sub.fOwnerPh': 'सहायक दस्तावेज़ अनुसार',
    'sub.fShareH': 'जैसे संयुक्त धारण हेतु 50%',
    'sub.fFileH': 'PDF / छवि, अधिकतम 10 MB',
    'sub.fSurvey': 'सर्वे संख्या',
    'sub.fSubdiv': 'उप-विभाग संख्या',
    'sub.fPlot': 'प्लॉट संख्या',
    'sub.fTower': 'टावर / ब्लॉक',
    'sub.fUsage': 'संपत्ति उपयोग',
    'sub.fParcelID': 'पार्सल ID',
    'sub.fLandUse': 'भू-उपयोग',
    'sub.fBoundary': 'सीमा स्रोत',
    'sub.fBldName': 'भवन नाम',
    'sub.fBldId': 'भवन ID',
    'sub.fBldType': 'भवन प्रकार',
    'sub.fFloors': 'तलों की संख्या',
    'sub.fBasements': 'बेसमेंट',
    'sub.fConstYr': 'निर्माण वर्ष',
    'sub.fApprRef': 'भवन अनुमोदन संदर्भ',
    'sub.fComplete': 'पूर्णता / अधिभोग',
    'sub.fFloorNo': 'तल संख्या',
    'sub.fFloorUse': 'तल उपयोग',
    'sub.fFloorPlan': 'फ्लोर प्लान उपलब्ध',
    'sub.yes': 'हां',
    'sub.no': 'नहीं',
    'sub.fUnitNo': 'इकाई / फ्लैट संख्या',
    'sub.fUnitType': 'इकाई प्रकार',
    'sub.fUtilType': 'उपयोगिता प्रकार',
    'sub.fDepth': 'गहराई (मी., ऋणात्मक)',
    'sub.fInstYr': 'स्थापना वर्ष',
    'sub.fAffParcels': 'प्रभावित पार्सल',
    'sub.fState': 'राज्य',
    'sub.fDistrict': 'जिला',
    'sub.fTehsil': 'उप-जिला / तहसील',
    'sub.fCity': 'शहर / कस्बा / गांव',
    'sub.fWard': 'वार्ड',
    'sub.fLocality': 'मोहल्ला',
    'sub.fColony': 'कॉलोनी / सोसायटी',
    'sub.fStreet': 'गली / सड़क',
    'sub.fPin': 'पिन कोड',
    'sub.fLandmark': 'पहचान चिह्न',
    'sub.fLat': 'अक्षांश',
    'sub.fLng': 'देशांतर',
    'sub.fCoordSrc': 'निर्देशांक स्रोत',
    'sub.fAcc': 'परिशुद्धता (मी.)',
    'sub.fSurveyDate': 'सर्वेक्षण तिथि',
    'sub.mLength': 'लंबाई (मी.)',
    'sub.mWidth': 'चौड़ाई (मी.)',
    'sub.mHeight': 'ऊंचाई (मी.)',
    'sub.mDepth': 'गहराई (मी.)',
    'sub.mPerim': 'परिमाप (मी.)',
    'sub.mBldH': 'भवन ऊंचाई (मी.)',
    'sub.mFloorH': 'तल ऊंचाई (मी.)',
    'sub.mBaseDepth': 'बेसमेंट गहराई (मी.)',
    'sub.mGround': 'भूमि ऊंचाई (मी.)',
    'sub.mZmin': 'Z-न्यून (मी.)',
    'sub.mZmax': 'Z-अधिक (मी.)',
    'sub.mElevSrc': 'ऊंचाई स्रोत',
    'sub.vertExt': 'लंबवत विस्तार: {v} मी.',
    'sub.fOwner': 'स्वामी / अधिकार धारक',
    'sub.fOwnerRef': 'स्वामित्व संदर्भ',
    'sub.fOwnerType': 'स्वामित्व प्रकार',
    'sub.fRightType': 'अधिकार प्रकार',
    'sub.fRegRef': 'पंजीकरण संदर्भ',
    'sub.fShare': 'स्वामित्व हिस्सा',
    'sub.fLeaseNotes': 'पट्टा / सुखाचार टिप्पणी',
    'sub.fDocType': 'दस्तावेज़ प्रकार',
    'sub.fFile': 'फ़ाइल',
    'sub.fDocNo': 'दस्तावेज़ संख्या',
    'sub.fDocDate': 'दस्तावेज़ तिथि',
    'sub.fAuthority': 'जारीकर्ता प्राधिकरण',
    'sub.fDesc': 'विवरण',
    'sub.rProp': 'संपत्ति',
    'sub.rIntent': 'उद्देश्य',
    'sub.rParcel': 'पार्सल',
    'sub.rBld': 'भवन',
    'sub.rFloor': 'तल',
    'sub.rUnit': 'इकाई',
    'sub.rArea': 'क्षेत्र',
    'sub.rVert': 'ऊंचाई',
    'sub.rOwner': 'स्वामी (दावा)',
    'sub.rDocs': 'दस्तावेज़',
    'sub.rSource': 'स्रोत',
    'sub.rStatus': 'जमा पर स्थिति',
    'sub.rNew': 'नया पंजीकरण',
    'sub.rUpd': 'मौजूदा अद्यतन',
    'sub.rUploaded': 'अपलोडेड',
    'sub.rDept': 'अधिकृत विभाग ({v})',
    'sub.rOwnerUnv': 'संपत्ति स्वामी (असत्यापित)',
    'sub.rValInt': 'मान्य → एकीकृत / समीक्षा आवश्यक',
    'sub.rPendHum': 'मानव सत्यापन लंबित',
    'sub.aiAssist': 'AI सहायता: {v}',
    'sub.ownerClaim': 'संपत्ति स्वामी / नागरिक आवेदन। आपकी जानकारी सत्यापन तक दावा है — भू-डेटा बनने से पहले अधिकारी इसकी समीक्षा करता है।',
    'trk.newReg': 'नया पंजीकरण',
    'trk.upd': 'अद्यतन',
    'trk.fields': 'फ़ील्ड: {v}',
    'trk.meas': 'माप:',
    'trk.rSurvey': 'सर्वेक्षण',
    'trk.rAddr': 'पता',
    'trk.rCoords': 'निर्देशांक',
    'trk.rRight': 'अधिकार',
    'q.aria': 'कतार फ़िल्टर',
    'q.subStatus': 'आवेदन {v}',
    'q.meas': 'माप:',
    'q.claimed': 'दावाकृत: {v}',
    'q.openField': 'क्षेत्र अभिलेख खोलें',
    'q.c1': 'संपत्ति मौजूद',
    'q.c2': 'पता मेल खाता',
    'q.c3': 'पार्सल सीमा मेल खाती',
    'q.c4': 'भवन मौजूद',
    'q.c5': 'तल मौजूद',
    'q.c6': 'इकाई मौजूद',
    'q.c7': 'माप सत्यापित',
    'q.c8': 'निर्देशांक जांचे',
    'q.c9': 'दस्तावेज़ जांचे',
    'q.c10': 'फोटो संग्रहित',
    'fw.you': '(आप)',
    'fw.ariaStatus': 'स्थिति फ़िल्टर',
    'map.utilNotFound': 'उपयोगिता नहीं मिली',
    'map.loadFail': 'विवरण लोड विफल',
    'map.prevTitle': 'पूर्वावलोकन: {v}',
    'map.prevSub': '{n} फ़ीचर · धराशायी सियान · अभी सहेजा नहीं',
    'map.floors': 'तल',
    'map.height': 'ऊंचाई',
    'map.conf': 'विश्वास',
    'map.parcelX': 'पार्सल {v}',
    'map.affParcels': 'प्रभावित पार्सल: {v}',
    'map.blds': 'भवन ({n})',
    'map.flConf': '{f} तल · {c}%',
    'map.underX': '{n} भूमिगत संपत्तियां इस पार्सल को काटती हैं: {v}',
    'map.sqft': 'वर्ग फुट',
    'v3d.crumbDash': 'डैशबोर्ड',
    'v3d.crumbMap': 'मानचित्र',
    'v3d.resetCam': 'कैमरा रीसेट करें',
    'v3d.legend': 'संकेत:',
    'v3d.lSlab': 'तल स्लैब',
    'v3d.lRooms': 'कमरे (टैग संख्या दिखाते हैं)',
    'v3d.lUnv': 'असत्यापित कमरा',
    'v3d.lSel': 'चयनित कमरा · कमरा/टैग क्लिक करें',
    'v3d.lSelF': 'चयनित तल',
    'v3d.lVer': 'सत्यापित',
    'v3d.lRev': 'समीक्षा',
    'v3d.lBase': 'बेसमेंट',
    'v3d.lUnits': 'इकाइयां',
    'v3d.lSelU': 'चयनित इकाई · घुमाने हेतु ड्रैग · ज़ूम हेतु स्क्रॉल · तल/इकाई क्लिक करें',
    'v3d.underNote': 'भूमिगत दृश्य: भूतल के नीचे जल / विद्युत / सीवर / टेलीकॉम / गैस / मेट्रो ट्यूब (भूमि अर्ध-पारदर्शी)।',
    'v3d.proto': 'प्रोटोटाइप 3D ULPIN:',
    'v3d.iid': 'आंतरिक ID:',
    'v3d.rParcel': 'पार्सल:',
    'v3d.rFloor': 'तल:',
    'v3d.rArea': 'क्षेत्र:',
    'v3d.rVert': 'ऊंचाई:',
    'v3d.rType': 'प्रकार:',
    'v3d.rOwner': 'स्वामी:',
    'v3d.missing': '— अनुपलब्ध',
    'v3d.towerRail': '— टावर रेल',
    'rep.bySev': 'गंभीरता अनुसार:',
    'rep.bySt': 'स्थिति अनुसार:',
    'rep.valSumN': 'सत्यापन सारांश — {n} खुली समस्याएं',
    'val.page': '{n} समस्याएं · पृष्ठ {p}',
    'adm.sParcels': 'पार्सल',
    'adm.sBld': 'भवन',
    'adm.sUnits': 'इकाइयां',
    'adm.sOpen': 'खुली समस्याएं',
    'adm.sUtils': 'उपयोगिताएं',
    'adm.sVer': 'सत्यापित इकाइयां',
    'adm.sNeeds': 'समीक्षा आवश्यक',
    'adm.sAvg': 'औसत विश्वास',
    'adm.verifiedGe': 'सत्यापित ≥',
    'adm.highGe': 'उच्च ≥',
    'adm.revGe': 'समीक्षा ≥',
    'adm.saveBtn': 'सहेजें',
    'adm.allOpt': 'सभी',
    'adm.last': 'अंतिम: {v}',
    'adm.feat': 'फ़ीचर',
    'adm.bbox': 'बबॉक्स {v}',
    'ai.conf': '· AI विश्वास {v}%',
    'ai.close': 'सहायक बंद करें',
    'ai.ask': 'सहायक से पूछें',
    'ai.send': 'प्रश्न भेजें',
    'tour.copilotHi': 'सहायक: {n} ऊंचाई अंतर हाइलाइट',
    'tour.copilotDown': 'सहायक अनुपलब्ध: {e}',
    'tour.autoT': 'स्वतः-प्ले टॉगल करें',
    'tour.endT': 'भ्रमण समाप्त करें',
    'dash.scaleAria': 'संख्या पैमाना',
    'sub.fExistUlp': 'मौजूदा ULPIN / संदर्भ',
    'sub.fUtil': 'भूमिगत संपत्ति',
    'q.rUlp': 'ULPIN संदर्भ',
    'q.rPlot': 'प्लॉट',
    'q.rFloors': 'तल',
    'q.rUsage': 'उपयोग',
    'q.rHeight': 'ऊंचाई',
    'q.existArea': 'क्षेत्र {a} वर्ग फुट · z {zmin}–{zmax} मी. · {s} · {c}%',
    'rep.rStatus': 'स्थिति',
    'rep.rConf': 'विश्वास',
    'rep.rOwner': 'स्वामी',
    'rep.rType': 'प्रकार',
    'rep.missing': '— अनुपलब्ध',
    'val.sevAria': 'गंभीरता फ़िल्टर',
    'val.stAria': 'स्थिति फ़िल्टर',
    'v3d.parcelAssets': ' पार्सल {p} → {n} प्रतिच्छेदी संपत्ति ({v})।',
    'v3d.repUlp': 'ULPIN:',
    'v3d.repParcel': 'पार्सल {p} · {b} · {f} · इकाई {u}',
    'v3d.repArea': 'क्षेत्र {a} वर्ग फुट · z {z}मी. · {s} · {c}%',
    'v3d.repOwner': 'स्वामी: {v} ({r})',
    'tour.guided': 'निर्देशित डेमो',
    'tour.back': 'पीछे',
    'tour.next': 'आगे',
    'tour.finish': 'भ्रमण समाप्त',
    'tour.skip': 'भ्रमण छोड़ें',
    'tour.auto': 'स्वतः-प्ले (9 से./चरण)',
    'tour.pause': 'स्वतः-प्ले रोकें',
  },
};
