/** Public portal page strings: home, verify, property, citizen home, static pages. */
export const dict = {
  en: {
    // home hero
    'home.badge': 'SIH 2026 PROTOTYPE · DILRMP-INSPIRED',
    'home.titleA': 'Vertical property records, ',
    'home.titleB': 'floor by floor,',
    'home.titleC': 'unit by unit.',
    'home.sub': 'BhuSphere 3D demonstrates how parcels, buildings, floors and apartments can be mapped as 3D spatial volumes — with validation, QR identity and a citizen submission workflow aligned to Digital India Land Records Modernisation Programme concepts.',
    'home.verify': 'Verify property',
    'home.submit': 'Submit property data',
    'home.learn': 'Learn more',
    'home.nologin': 'No login needed to verify · Demo data only · Hindi / English',
    'home.stack': 'Property stack',
    'home.stackSub': 'Parcel → building → floor → unit',
    'home.bandK': 'Verify property',
    'home.bandT': 'Have a reference? Check it in seconds.',
    'home.bandS': 'Enter the demo reference from a QR or notice. Public mode shows geometry and verification status only — no login needed.',
    'home.refLabel': 'Property reference (demo ULPIN)',
    'home.verifyBtn': 'Verify →',
    'home.trust1t': 'Bhu-Aadhaar concept',
    'home.trust1d': 'Demo ULPINs show parcel → unit lineage like the national ULPIN idea.',
    'home.trust2t': 'DILRMP-aligned flow',
    'home.trust2d': 'Submit → validate → officer verification → approval. No bypass.',
    'home.trust3t': 'QR for every unit',
    'home.trust3d': 'Public identity carries safe fields only — no sensitive owner data.',
    'home.svcK': 'Citizen services',
    'home.svcT': 'What can you do here?',
    'home.svcS': 'Six starting points. Public checks need no login — workspace actions sign you in.',
    'home.svcAll': 'All services →',
    'home.howK': 'How it works',
    'home.howT': 'From submission to verified record',
    'home.howS': 'Four clear stages. Nothing becomes official until an authorised officer approves it.',
    'home.claimNote': 'Citizen submissions are unverified claims until an authorised officer approves them. Ownership details never establish legal title.',
    'home.notices': 'Notices & updates',
    'home.demoBoard': 'Demo board',
    'home.whoK': 'Who is this for?',
    'home.whoT': 'One portal, role-based workspaces',
    'home.whoS': 'Sign in after exploring — each role sees only its own workspace.',
    'home.aud1t': 'Property Owner / Citizen',
    'home.aud1d': 'Submit, track, correction, QR identity. No system counts — only your services.',
    'home.aud2t': 'Government Officer',
    'home.aud2d': 'Verification queue, approvals, validation centre, reports, audit trail.',
    'home.aud3t': 'Surveyor',
    'home.aud3d': 'Field checks, geometry inspection, measurement verification.',
    'home.signin': 'Sign in to workspace',
    'home.readFaq': 'Read FAQs',
    'home.ctaT': 'Start with a public check — no account needed.',
    'home.ctaS': 'Verify a demo property, then explore the map, 3D stack, or submission flow at your own pace.',
    'home.ctaHow': 'How it works',
    // verify
    'verify.kicker': 'Verify property',
    'verify.title': 'Verify a property identity',
    'verify.sub': 'Enter the demo reference from a QR or notice. Public mode shows geometry, verification status and reference only.',
    'verify.label': 'Property reference / demo ULPIN',
    'verify.btn': 'Verify',
    'verify.busy': 'Verifying…',
    'verify.notfound': 'Property not found for {id}. Check the reference or QR and try again.',
    'verify.cardTitle': 'Public property identity',
    'verify.confLine': 'Confidence {v}% · Ownership detail requires an authorised role.',
    'verify.openFull': 'Open full identity card →',
    'verify.whatMean': 'What does this mean?',
    'verify.toolTitle': 'Verify property',
    'verify.toolSub': 'Enter the demo reference from a QR or notice. Public fields only — ownership detail stays restricted.',
    // property
    'prop.title': 'Property Digital Identity',
    'prop.loading': 'Loading property identity…',
    'prop.notfound': 'Property not found',
    'prop.check': 'Check the reference or QR code and try again.',
    'prop.verifyAnother': 'Verify another',
    'prop.portalHome': 'Portal home',
    'prop.foot': 'Public mode: geometry, verification status and reference only. Ownership detail requires an authorized role.',
    // identity facts
    'facts.title': 'Record details',
    'facts.addr': 'Address / location',
    'facts.geo': 'Geolocation',
    'facts.type': 'Property type',
    'facts.own': 'Ownership / legal flag',
    'facts.ownNone': 'Not recorded',
    'facts.reg': 'Registration / mutation status',
    'facts.auth': 'Data source / issuing authority',
    'facts.updated': 'Last updated / verified',
    // citizen home
    'ch.hello': 'Namaste{name} 🙏',
    'ch.title': 'Property Owner Service Portal',
    'ch.sub': 'Submit your property information, track verification, and verify identities — without needing to read any system-wide registers or maps jargon.',
    'ch.submit': 'Submit property data',
    'ch.my': 'My submissions',
    'ch.verify': 'Verify property',
    'ch.verifyBox': 'Verify a property reference',
    'ch.verifyBoxS': 'From a QR, notice or allotment letter (demo IDs only).',
    'ch.new3': 'New here? 3 steps',
    'ch.s1': 'Submit — fill the guided form; documents optional.',
    'ch.s2': 'Track — watch validation → officer review on your timeline.',
    'ch.s3': 'Fix if asked — resubmit corrections from My Submissions.',
    'ch.how': 'How it works',
    'ch.myT': 'My submissions',
    'ch.myS': 'Only yours — newest first',
    'ch.inprog': 'in progress',
    'ch.newSub': '+ New submission',
    'ch.empty': 'No submissions yet.',
    'ch.startFirst': 'Start your first submission →',
    'ch.services': 'Services',
    'ch.sc1t': 'Submit / update',
    'ch.sc1d': 'Guided property form with map pick.',
    'ch.sc2t': 'Track status',
    'ch.sc2d': 'Timeline + officer notes + corrections.',
    'ch.sc3t': 'Verify identity',
    'ch.sc3d': 'Public QR/reference check.',
    'ch.sc4t': 'Help & contact',
    'ch.sc4d': 'FAQs, guides and helpdesk.',
    // about
    'about.kicker': 'About us',
    'about.title': 'About BhuSphere 3D',
    'about.sub': 'A Smart India Hackathon 2026 prototype for vertical property mapping — showing how India\u2019s land-records ideas (DILRMP, ULPIN/Bhu-Aadhaar, Bhu-Naksha) extend naturally into 3D.',
    'about.mission': 'Mission',
    'about.m1': 'Urban India stacks homes vertically — but most cadastral maps stop at the ground parcel. BhuSphere 3D prototypes a parcel → building → floor → unit volume model so apartments, basements and utilities each carry identity, geometry, evidence and verification state.',
    'about.m2': 'It fuses GIS, LiDAR-derived heights, drone/survey evidence and floor plans, then runs AI-assisted topology checks. Every finding needs human review — the system never auto-declares truth.',
    'about.aligned': 'Aligned to national programmes',
    'about.is': 'What this prototype IS',
    'about.isNot': 'What it is NOT',
    // services page
    'svc.kicker': 'Services',
    'svc.title': 'Citizen & department services',
    'svc.sub': 'Start here. Public services need no login; workspace actions sign you in with a demo role.',
    'svc.note': 'Map and 3D workspaces open in the signed-in demo. Sign in as citizen / demo123 to submit and explore.',
    // how it works
    'hiw.kicker': 'How it works',
    'hiw.title': 'How property data becomes a verified record',
    'hiw.sub': 'Two lanes: citizen claims that must be verified, and authorised department sources that skip the citizen queue.',
    'hiw.owner': 'Property owner',
    'hiw.officer': 'Officer / dept',
    'hiw.start': 'Start as property owner',
    'hiw.verifyFirst': 'Verify a property first',
    // help
    'help.kicker': 'Help',
    'help.title': 'Help & frequently asked questions',
    'help.sub': 'Short answers for citizens, departments and evaluators. Demo logins use password demo123.',
    'help.accounts': 'Demo accounts',
    'help.login': 'Go to login',
    'help.contact': 'Contact helpdesk',
    'help.toolTitle': 'Help & FAQs',
    'help.toolSub': 'Answers for your workspace. Demo logins use password demo123.',
    // contact
    'ct.toolTitle': 'Contact helpdesk',
    'ct.toolSub': 'Demo helpdesk — enquiries stay in your browser only.',
    'ct.kicker': 'Contact us',
    'ct.title': 'Contact the helpdesk',
    'ct.sub': 'Demo helpdesk — enquiries are saved in your browser only and are never sent to a real department.',
    'ct.saved': 'Enquiry {id} saved locally (demo). Our team would respond within 2 working days on a live portal.',
    'ct.name': 'Full name *',
    'ct.email': 'Email',
    'ct.topic': 'Topic',
    'ct.msg': 'Message *',
    'ct.msgPh': 'Describe your query…',
    'ct.send': 'Submit enquiry (demo)',
    'ct.hd': 'Helpdesk (Demo)',
    'ct.hours': '1800-XXX-XXXX · Mon–Fri, 9am–5:30pm',
    'ct.note': 'For land disputes, registration or RoR corrections, please approach your State Revenue Department / Sub-Registrar Office. This demo cannot change official records.',
  },
  hi: {
    'home.badge': 'SIH 2026 प्रोटोटाइप · DILRMP-प्रेरित',
    'home.titleA': 'त्रि-आयामी संपत्ति अभिलेख, ',
    'home.titleB': 'मंज़िल दर मंज़िल,',
    'home.titleC': 'इकाई दर इकाई।',
    'home.sub': 'भूस्फीयर 3D दिखाता है कि पार्सल, भवन, तल और अपार्टमेंट को 3D स्थानिक आयतन के रूप में कैसे mapped किया जा सकता है — सत्यापन, QR पहचान और Digital India भू-अभिलेख आधुनिकीकरण कार्यक्रम की अवधारणाओं के अनुरूप नागरिक जमा कार्यप्रवाह सहित।',
    'home.verify': 'संपत्ति सत्यापित करें',
    'home.submit': 'संपत्ति डेटा जमा करें',
    'home.learn': 'और जानें',
    'home.nologin': 'सत्यापन हेतु लॉगिन आवश्यक नहीं · केवल डेमो डेटा · हिन्दी / English',
    'home.stack': 'संपत्ति संरचना',
    'home.stackSub': 'पार्सल → भवन → तल → इकाई',
    'home.bandK': 'संपत्ति सत्यापित करें',
    'home.bandT': 'संदर्भ है? सेकंडों में जांचें।',
    'home.bandS': 'QR या नोटिस से डेमो संदर्भ दर्ज करें। सार्वजनिक मोड में केवल ज्यामिति और सत्यापन स्थिति दिखती है — लॉगिन आवश्यक नहीं।',
    'home.refLabel': 'संपत्ति संदर्भ (डेमो ULPIN)',
    'home.verifyBtn': 'सत्यापित करें →',
    'home.trust1t': 'भू-आधार अवधारणा',
    'home.trust1d': 'डेमो ULPIN राष्ट्रीय ULPIN विचार की तरह पार्सल → इकाई वंशावली दिखाते हैं।',
    'home.trust2t': 'DILRMP-अनुरूप प्रवाह',
    'home.trust2d': 'जमा करें → मान्य करें → अधिकारी सत्यापन → अनुमोदन। कोई बाइपास नहीं।',
    'home.trust3t': 'प्रत्येक इकाई हेतु QR',
    'home.trust3d': 'सार्वजनिक पहचान में केवल सुरक्षित फ़ील्ड — कोई संवेदनशील स्वामी डेटा नहीं।',
    'home.svcK': 'नागरिक सेवाएं',
    'home.svcT': 'आप यहां क्या कर सकते हैं?',
    'home.svcS': 'छह प्रारंभिक बिंदु। सार्वजनिक जांच हेतु लॉगिन नहीं — कार्यक्षेत्र क्रियाएं आपको साइन इन कराती हैं।',
    'home.svcAll': 'सभी सेवाएं →',
    'home.howK': 'यह कैसे काम करता है',
    'home.howT': 'जमा करने से सत्यापित अभिलेख तक',
    'home.howS': 'चार स्पष्ट चरण। अधिकृत अधिकारी के अनुमोदन तक कुछ भी आधिकारिक नहीं बनता।',
    'home.claimNote': 'अधिकृत अधिकारी के अनुमोदन तक नागरिक आवेदन असत्यापित दावे हैं। स्वामित्व विवरण कभी कानूनी स्वामित्व स्थापित नहीं करते।',
    'home.notices': 'सूचनाएं व अद्यतन',
    'home.demoBoard': 'डेमो बोर्ड',
    'home.whoK': 'यह किसके लिए है?',
    'home.whoT': 'एक पोर्टल, भूमिका-आधारित कार्यक्षेत्र',
    'home.whoS': 'एक्सप्लोर करने के बाद साइन इन करें — प्रत्येक भूमिका केवल अपना कार्यक्षेत्र देखती है।',
    'home.aud1t': 'संपत्ति स्वामी / नागरिक',
    'home.aud1d': 'जमा करें, ट्रैक करें, सुधार, QR पहचान। कोई सिस्टम गणना नहीं — केवल आपकी सेवाएं।',
    'home.aud2t': 'सरकारी अधिकारी',
    'home.aud2d': 'सत्यापन कतार, अनुमोदन, सत्यापन केंद्र, रिपोर्ट, ऑडिट ट्रेल।',
    'home.aud3t': 'सर्वेक्षक',
    'home.aud3d': 'क्षेत्र जांच, ज्यामिति निरीक्षण, माप सत्यापन।',
    'home.signin': 'कार्यक्षेत्र में साइन इन करें',
    'home.readFaq': 'सामान्य प्रश्न पढ़ें',
    'home.ctaT': 'सार्वजनिक जांच से शुरुआत करें — खाते की आवश्यकता नहीं।',
    'home.ctaS': 'डेमो संपत्ति सत्यापित करें, फिर मानचित्र, 3D संरचना या जमा प्रवाह अपनी गति से एक्सप्लोर करें।',
    'home.ctaHow': 'यह कैसे काम करता है',
    'verify.kicker': 'संपत्ति सत्यापित करें',
    'verify.title': 'संपत्ति पहचान सत्यापित करें',
    'verify.sub': 'QR या नोटिस से डेमो संदर्भ दर्ज करें। सार्वजनिक मोड में केवल ज्यामिति, सत्यापन स्थिति और संदर्भ दिखता है।',
    'verify.label': 'संपत्ति संदर्भ / डेमो ULPIN',
    'verify.btn': 'सत्यापित करें',
    'verify.busy': 'सत्यापित हो रहा है…',
    'verify.notfound': '{id} हेतु संपत्ति नहीं मिली। संदर्भ या QR जांचकर पुनः प्रयास करें।',
    'verify.cardTitle': 'सार्वजनिक संपत्ति पहचान',
    'verify.confLine': 'विश्वास {v}% · स्वामित्व विवरण हेतु अधिकृत भूमिका आवश्यक।',
    'verify.openFull': 'पूर्ण पहचान कार्ड खोलें →',
    'verify.whatMean': 'इसका क्या अर्थ है?',
    'verify.toolTitle': 'संपत्ति सत्यापित करें',
    'verify.toolSub': 'QR या नोटिस से डेमो संदर्भ दर्ज करें। केवल सार्वजनिक फ़ील्ड — स्वामित्व विवरण प्रतिबंधित रहता है।',
    'prop.title': 'संपत्ति डिजिटल पहचान',
    'prop.loading': 'संपत्ति पहचान लोड हो रही है…',
    'prop.notfound': 'संपत्ति नहीं मिली',
    'prop.check': 'संदर्भ या QR कोड जांचकर पुनः प्रयास करें।',
    'prop.verifyAnother': 'अन्य सत्यापित करें',
    'prop.portalHome': 'पोर्टल होम',
    'prop.foot': 'सार्वजनिक मोड: केवल ज्यामिति, सत्यापन स्थिति और संदर्भ। स्वामित्व विवरण हेतु अधिकृत भूमिका आवश्यक।',
    'facts.title': 'अभिलेख विवरण',
    'facts.addr': 'पता / स्थान',
    'facts.geo': 'भौगोलिक स्थिति',
    'facts.type': 'संपत्ति प्रकार',
    'facts.own': 'स्वामित्व / कानूनी स्थिति',
    'facts.ownNone': 'दर्ज नहीं',
    'facts.reg': 'पंजीकरण / दाखिल-खारिज स्थिति',
    'facts.auth': 'डेटा स्रोत / जारीकर्ता प्राधिकरण',
    'facts.updated': 'अंतिम अद्यतन / सत्यापित',
    'ch.hello': 'नमस्ते{name} 🙏',
    'ch.title': 'संपत्ति स्वामी सेवा पोर्टल',
    'ch.sub': 'अपनी संपत्ति जानकारी जमा करें, सत्यापन ट्रैक करें और पहचान सत्यापित करें — बिना किसी सिस्टम-व्यापी रजिस्टर या मानचित्र शब्दावली के।',
    'ch.submit': 'संपत्ति डेटा जमा करें',
    'ch.my': 'मेरे आवेदन',
    'ch.verify': 'संपत्ति सत्यापित करें',
    'ch.verifyBox': 'संपत्ति संदर्भ सत्यापित करें',
    'ch.verifyBoxS': 'QR, नोटिस या आवंटन पत्र से (केवल डेमो ID)।',
    'ch.new3': 'नए हैं? 3 चरण',
    'ch.s1': 'जमा करें — निर्देशित फ़ॉर्म भरें; दस्तावेज़ वैकल्पिक।',
    'ch.s2': 'ट्रैक करें — अपनी टाइमलाइन पर सत्यापन → अधिकारी समीक्षा देखें।',
    'ch.s3': 'कहा जाए तो सुधारें — मेरे आवेदनों से सुधार पुनः जमा करें।',
    'ch.how': 'यह कैसे काम करता है',
    'ch.myT': 'मेरे आवेदन',
    'ch.myS': 'केवल आपके — नवीनतम पहले',
    'ch.inprog': 'प्रगति पर',
    'ch.newSub': '+ नया आवेदन',
    'ch.empty': 'अभी कोई आवेदन नहीं।',
    'ch.startFirst': 'अपना पहला आवेदन शुरू करें →',
    'ch.services': 'सेवाएं',
    'ch.sc1t': 'जमा / अद्यतन करें',
    'ch.sc1d': 'मानचित्र चयन सहित निर्देशित संपत्ति फ़ॉर्म।',
    'ch.sc2t': 'स्थिति ट्रैक करें',
    'ch.sc2d': 'टाइमलाइन + अधिकारी टिप्पणी + सुधार।',
    'ch.sc3t': 'पहचान सत्यापित करें',
    'ch.sc3d': 'सार्वजनिक QR/संदर्भ जांच।',
    'ch.sc4t': 'सहायता व संपर्क',
    'ch.sc4d': 'सामान्य प्रश्न, मार्गदर्शिकाएं और हेल्पडेस्क।',
    'about.kicker': 'हमारे बारे में',
    'about.title': 'भूस्फीयर 3D के बारे में',
    'about.sub': 'त्रि-आयामी संपत्ति मानचित्रण हेतु स्मार्ट इंडिया हैकाथॉन 2026 प्रोटोटाइप — भारत के भू-अभिलेख विचार (DILRMP, ULPIN/भू-आधार, भू-नक्शा) स्वाभाविक रूप से 3D में कैसे विस्तारित होते हैं।',
    'about.mission': 'लक्ष्य',
    'about.m1': 'शहरी भारत में घर लंबवत बनते हैं — पर अधिकांश भू-मानचित्र जमीनी पार्सल पर रुक जाते हैं। भूस्फीयर 3D पार्सल → भवन → तल → इकाई आयतन मॉडल का प्रोटोटाइप है ताकि अपार्टमेंट, बेसमेंट और उपयोगिताओं की पहचान, ज्यामिति, साक्ष्य और सत्यापन स्थिति हो।',
    'about.m2': 'यह GIS, LiDAR-व्युत्पन्न ऊंचाइयों, ड्रोन/सर्वेक्षण साक्ष्य और फ्लोर प्लान को जोड़ता है, फिर AI-सहायित टोपोलॉजी जांच चलाता है। प्रत्येक निष्कर्ष हेतु मानव समीक्षा आवश्यक है — सिस्टम कभी स्वतः सत्य घोषित नहीं करता।',
    'about.aligned': 'राष्ट्रीय कार्यक्रमों के अनुरूप',
    'about.is': 'यह प्रोटोटाइप क्या है',
    'about.isNot': 'यह क्या नहीं है',
    'svc.kicker': 'सेवाएं',
    'svc.title': 'नागरिक व विभागीय सेवाएं',
    'svc.sub': 'यहां से शुरुआत करें। सार्वजनिक सेवाओं हेतु लॉगिन नहीं; कार्यक्षेत्र क्रियाएं डेमो भूमिका से साइन इन कराती हैं।',
    'svc.note': 'मानचित्र और 3D कार्यक्षेत्र साइन-इन डेमो में खुलते हैं। जमा करने व एक्सप्लोर करने हेतु citizen / demo123 से साइन इन करें।',
    'hiw.kicker': 'यह कैसे काम करता है',
    'hiw.title': 'संपत्ति डेटा सत्यापित अभिलेख कैसे बनता है',
    'hiw.sub': 'दो मार्ग: नागरिक दावे जिनका सत्यापन आवश्यक है, और अधिकृत विभागीय स्रोत जो नागरिक कतार में नहीं जाते।',
    'hiw.owner': 'संपत्ति स्वामी',
    'hiw.officer': 'अधिकारी / विभाग',
    'hiw.start': 'संपत्ति स्वामी के रूप में शुरू करें',
    'hiw.verifyFirst': 'पहले संपत्ति सत्यापित करें',
    'help.kicker': 'सहायता',
    'help.title': 'सहायता व अक्सर पूछे जाने वाले प्रश्न',
    'help.sub': 'नागरिकों, विभागों और मूल्यांककों हेतु संक्षिप्त उत्तर। डेमो लॉगिन में पासवर्ड demo123 प्रयोग होता है।',
    'help.accounts': 'डेमो खाते',
    'help.login': 'लॉगिन पर जाएं',
    'help.contact': 'हेल्पडेस्क से संपर्क करें',
    'help.toolTitle': 'सहायता व सामान्य प्रश्न',
    'help.toolSub': 'आपके कार्यक्षेत्र हेतु उत्तर। डेमो लॉगिन में पासवर्ड demo123 प्रयोग होता है।',
    'ct.toolTitle': 'हेल्पडेस्क से संपर्क करें',
    'ct.toolSub': 'डेमो हेल्पडेस्क — पूछताछ केवल आपके ब्राउज़र में रहती है।',
    'ct.kicker': 'संपर्क करें',
    'ct.title': 'हेल्पडेस्क से संपर्क करें',
    'ct.sub': 'डेमो हेल्पडेस्क — पूछताछ केवल आपके ब्राउज़र में सहेजी जाती है, किसी वास्तविक विभाग को नहीं भेजी जाती।',
    'ct.saved': 'पूछताछ {id} स्थानीय रूप से सहेजी गई (डेमो)। लाइव पोर्टल पर हमारी टीम 2 कार्यदिवसों में उत्तर देगी।',
    'ct.name': 'पूरा नाम *',
    'ct.email': 'ईमेल',
    'ct.topic': 'विषय',
    'ct.msg': 'संदेश *',
    'ct.msgPh': 'अपनी पूछताछ लिखें…',
    'ct.send': 'पूछताछ भेजें (डेमो)',
    'ct.hd': 'हेल्पडेस्क (डेमो)',
    'ct.hours': '1800-XXX-XXXX · सोम–शुक्र, सुबह 9–शाम 5:30',
    'ct.note': 'भूमि विवाद, पंजीकरण या RoR सुधार हेतु कृपया अपने राज्य राजस्व विभाग / उप-पंजीयक कार्यालय से संपर्क करें। यह डेमो आधिकारिक अभिलेख नहीं बदल सकता।',
  },
};
